"""
Pico 2W MicroPython stepper/servo motor control script.

Supports three driver types per joint — mix and match as needed:

  "28byj"   — 28BYJ-48 with ULN2003 board (4 pins: IN1 IN2 IN3 IN4)
              Uses 8-step half-stepping sequence.
              Default steps_per_rev = 4096 (includes internal 64:1 gear).

  "stepdir" — NEMA 17/23 (or any step/dir motor) with A4988 / DRV8825 / TMC2209
              (2 pins: STEP DIR). STEP pulses are generated by PIO by default
              (``pio_stepdir`` true); DIR holds/setup from CPU. Set ``pio_stepdir``: false
              only to force GPIO STEP (debug).
              Set steps_per_rev to match your driver dip-switch (e.g. 800).
              Optional: "invert_dir": true to flip the DIR pin logic.

  "servo"   — Standard RC servo via PWM (1 pin: SIG).
              50 Hz PWM.  Angle maps linearly to pulse width (min_pulse_us–max_pulse_us).
              Default: 1000 µs = 0°, 2000 µs = 180°.
              Power servo from VBUS (5 V) — GPIO pin is signal only.
              Share GND between Pico and servo supply!

Protocol: USB serial by default. Optional WiFi TCP only if ENABLE_WIFI is True in the
deployed block (set when you deploy with an SSID, or edit ENABLE_WIFI manually).
When Wi‑Fi is enabled, the control loop serves the same commands over TCP — you can unplug
USB from the laptop once the Pico has joined Wi‑Fi, provided the board still has power
(USB to a charger, VSYS, etc.).

Standard message format (host → Pico):
    Host → Pico:  J0:45.00,J1:32.50,J2:10.00,J3:0.00\n
    Host → Pico:  T:<stream_seconds>,J0:45.00,...  (timestamped trajectory for ring buffer)\n
    Pico → Host:  OK\n   (or ERR:<message>\n on error)

Motion: the PC streams joint angles (optionally with ``T:`` timestamps); the firmware
interpolates a short lookahead buffer, maps to target steps, and follows with
accel/jerk-limited velocity (``accel`` / ``jerk`` / ``max_sps``). STEP/DIR (NEMA)
axes emit STEP from PIO when ``pio_stepdir`` is true (default); use ``pio_stepdir`` false
only for GPIO STEP debugging.
Homing still uses a simple local open-loop move toward a limit switch.

──────────────────────────────────────────────────────────────────────────────
CONFIGURATION — edit JOINTS; enable WiFi only via Deploy with SSID or ENABLE_WIFI=True
──────────────────────────────────────────────────────────────────────────────
"""

import sys
import time
import math
import errno
import select
import machine
from machine import Pin, PWM

# PIO STEP pulses for step/dir drivers (default). Software STEP only if ``pio_stepdir`` false.
try:
    import rp2
    from rp2 import PIO, StateMachine, asm_pio

    @asm_pio(set_init=PIO.OUT_LOW)
    def _pio_step_pulse_program():
        pull(block)
        mov(x, osr)
        label("wait_lo")
        jmp(x_dec, "wait_lo")
        set(pins, 1) [7]
        set(pins, 0)

    _PIO_HAVE_STEP = True
except Exception:
    # ImportError, asm_pio decode errors, etc. — stepdir needs ``pio_stepdir`` false for GPIO STEP
    _PIO_HAVE_STEP = False
    _pio_step_pulse_program = None

_PIO_SM_NEXT = 0


def _pio_alloc_sm_id(cfg: dict) -> int:
    """Assign a distinct PIO state machine index per step/dir axis."""
    global _PIO_SM_NEXT
    if "pio_sm" in cfg:
        return int(cfg["pio_sm"])
    i = _PIO_SM_NEXT
    _PIO_SM_NEXT = i + 1
    if i > 7:
        raise ValueError("Too many PIO step/dir axes (max 8 state machines)")
    return i

# When the host streams J0:..,J1:..,J2:.. but make_axis() skipped a JOINT, we
# record indices here and print a one-time WARN (otherwise J2 is ignored silently).
_SEEN_UNLOADED_J_CMD = set()

# WiFi is OFF unless you deploy with an SSID (sets ENABLE_WIFI True) or edit here.
# No network thread or TCP server — fastest control loop (USB serial only).
# <<BEGIN_WIFI_CONFIG>>
ENABLE_WIFI = False
WIFI_SSID = ""
WIFI_PASSWORD = ""
TCP_PORT = 8888
WIFI_COUNTRY = ""
# <<END_WIFI_CONFIG>>

# ---------------------------------------------------------------------------
# Half-step sequence for 28BYJ-48 (IN1 IN2 IN3 IN4)
# ---------------------------------------------------------------------------
_HALFSTEP = [
    [1, 0, 0, 0],
    [1, 1, 0, 0],
    [0, 1, 0, 0],
    [0, 1, 1, 0],
    [0, 0, 1, 0],
    [0, 0, 1, 1],
    [0, 0, 0, 1],
    [1, 0, 0, 1],
]

# ---------------------------------------------------------------------------
# JOINTS — edit pins, driver type, and motor parameters here
# The simulator GUI writes this block automatically when you click
# "Deploy Firmware".  You can also edit it manually.
# ---------------------------------------------------------------------------
# <<BEGIN_JOINTS_CONFIG>>
JOINTS = [
    # ── Joint 0: Base ── 28BYJ-48 on GP2/3/4/5
    {
        "idx": 0,
        "name": "Base",
        "driver": "28byj",          # "28byj" or "stepdir"
        "pins": [2, 3, 4, 5],       # [IN1, IN2, IN3, IN4]
        "steps_per_rev": 4096,      # 28BYJ-48 half-step incl. internal gear
        "gear_ratio": 1.0,          # additional external reduction (1.0 = none)
        "max_sps": 400,             # max steps/sec — 1 step/loop at ~400 Hz
        "accel": 500,               # steps/sec² — smooth ramp
        "zero_offset_deg": 0.0,     # angle added to compensate mech. zero
        "backlash_steps": 0,        # extra steps on direction reversal (start at 0, tune up)
        "gravity_offset_deg": 0.0,  # added to target to counteract gravitational sag
    },

    # ── Joint 1: Shoulder ── 28BYJ-48 on GP6/7/8/9
    {
        "idx": 1,
        "name": "Shoulder",
        "driver": "28byj",
        "pins": [6, 7, 8, 9],
        "steps_per_rev": 4096,
        "gear_ratio": 1.0,
        "max_sps": 900,
        "accel": 600,
        "zero_offset_deg": 0.0,
    },

    # ── Joint 2: Elbow ── 28BYJ-48 on GP10/11/12/13
    {
        "idx": 2,
        "name": "Elbow",
        "driver": "28byj",
        "pins": [10, 11, 12, 13],
        "steps_per_rev": 4096,
        "gear_ratio": 1.0,
        "max_sps": 900,
        "accel": 600,
        "zero_offset_deg": 0.0,
    },

    # ── Joint 3: Wrist ── 28BYJ-48 on GP14/15/16/17
    {
        "idx": 3,
        "name": "Wrist",
        "driver": "28byj",
        "pins": [14, 15, 16, 17],
        "steps_per_rev": 4096,
        "gear_ratio": 1.0,
        "max_sps": 900,
        "accel": 600,
        "zero_offset_deg": 0.0,
    },

    # ── Example: NEMA 17/23 on GP18/19
    # {
    #     "idx": 4,
    #     "name": "Gripper",
    #     "driver": "stepdir",
    #     "pins": [18, 19],           # [STEP, DIR]
    #     "steps_per_rev": 800,       # match your driver dip-switch setting
    #     "gear_ratio": 1.0,
    #     "invert_dir": False,        # True = flip DIR pin logic for this axis
    #     "max_sps": 2000,
    #     "accel": 1000,
    #     "zero_offset_deg": 0.0,
    # },

    # ── Example: RC servo on GP20 (uncomment to use as the last link)
    # Power servo from VBUS (5 V), share GND with Pico.
    # Angle mapping: simulator 0° → servo midpoint (centre pulse).
    #   sim  0°  → (min_pulse + max_pulse) / 2 = 1500 µs  (centre)
    #   sim +90° → max_pulse = 2000 µs
    #   sim -90° → min_pulse = 1000 µs
    # {
    #     "idx": 4,
    #     "name": "Gripper",
    #     "driver": "servo",
    #     "pins": [20],               # [SIG] — signal pin only
    #     "min_pulse_us": 1000,       # pulse at -angle_range/2   (500 µs = extended SG90)
    #     "max_pulse_us": 2000,       # pulse at +angle_range/2  (2500 µs = extended SG90)
    #     "angle_range_deg": 180,     # total travel (sim range ±90°)
    #     "zero_offset_deg": 0.0,     # shift if servo physical neutral ≠ simulator 0°
    # },
]
# <<END_JOINTS_CONFIG>>

# ---------------------------------------------------------------------------
# Control loop interval — how often axes are updated (microseconds)
# ---------------------------------------------------------------------------
# <<BEGIN_STEP_US_CONFIG>>
# Set at Deploy from the PC Hardware tab (main-loop period, µs).
STEP_US = 250
# <<END_STEP_US_CONFIG>>

# <<BEGIN_HOST_FOLLOW_SPS_CAP>>
# Global ceiling for host-follow step rate (full steps/s), set from the PC Hardware tab at Deploy.
# 0 = off — each joint uses its JOINTS max_sps as configured.
# N > 0 — let M = max(stepper max_sps in JOINTS). If M > N, every stepper's effective max_sps is
# scaled by (N/M) so the fastest joint runs at N and slower joints stay proportional (e.g. if
# J2=10000, J0=5000 and N=4000 → J2→4000, J0→2000). If M <= N, rates are unchanged.
HOST_FOLLOW_MAX_SPS = 0
# <<END_HOST_FOLLOW_SPS_CAP>>

# <<BEGIN_WEB_ARM_CONFIG>>
# Injected at Deploy from the PC Arm Configuration (matches simulator FK/IK).
WEB_HTTP_PORT = 8080
ARM_LINK_LENGTHS = []
ARM_JOINT_PLANE_OFFSETS = []
ARM_JOINT_LATERAL_X = []
ARM_JOINT_LATERAL_Y = []
ARM_BASE_VERTICAL_OFFSET = 0.0
ARM_JOINT_LIMITS_RAD = []
IK_USE_ELBOW_DOWN = True
# <<END_WEB_ARM_CONFIG>>

# Main loop: serial + motion + sleep each iteration. Shorter STEP_US → higher target loop
# rate (≈ 1/STEP_US kHz). Host follow can emit several full steps per axis per tick; if the
# loop overruns STEP_US, raise it or lower max_sps / MAX_STEPS_PER_AXIS_TICK.
# 28BYJ: if you miss steps, use longer STEP_US. NEMA: tune dir_setup_us and STEPT.

# Cap bursts toward streamed targets / STEPT (per axis, one update() call).
MAX_STEPS_PER_AXIS_TICK = 16
# Host-follow + homing use measured loop spacing (du_us). After a *slow* iteration — many
# interleaved steps on J1/J2 — du_us can be several× STEP_US; feeding that whole interval into
# one velocity integration dumps a step burst on the *next* pass (often felt as J0 surging).
# Cap dt passed to motion code at a few nominal control periods.
_MOTION_DT_MAX_MULT = 3.0
# Homing: one step per tick keeps limit-switch contact gentler; set False for faster search.
_HOMING_ONE_STEP_PER_TICK = True
# True: each axis plans up to MAX_STEPS/tick, then the main loop emits one step per axis per
# round (round-robin). All joints move together. False: each axis exhausts its burst before the
# next axis updates (looks like one joint at a time).
_HOST_INTERLEAVE_STEPS = True

# CNC-style trajectory ring (host ``T:<seconds>,J0:…`` lines).
TRAJ_RING_CAP = 48
TRAJ_LOOKAHEAD_S = 0.035

_traj_ring = None
_traj_anchor_us = None
_traj_prev_deg = ()
_traj_slots = 0

# Commands from WiFi HTTP dashboard → drained on main loop (thread-safe list append).
_web_cmd_queue = []
_http_axes_ref = None


def _clamp_scalar(v, lo, hi):
    return max(lo, min(hi, v))


def _axis_angle_deg(ax):
    """Joint angle in degrees (simulator convention) for FK / web display."""
    try:
        if hasattr(ax, "_steps_out") and ax._steps_out and ax._steps_out > 0:
            return ax.current_pos / ax._steps_out * 360.0 + getattr(ax, "zero_offset", 0.0)
        return float(getattr(ax, "target_pos", 0.0)) + float(getattr(ax, "zero_offset", 0.0))
    except Exception:
        return 0.0


def _angles_deg_bundle(axes):
    """(base_deg, planar_deg[]) aligned with ARM_LINK_LENGTHS."""
    by_idx = {a.idx: a for a in axes}
    bd = _axis_angle_deg(by_idx.get(0)) if 0 in by_idx else 0.0
    planar = []
    for i in range(len(ARM_LINK_LENGTHS)):
        ax = by_idx.get(i + 1)
        planar.append(_axis_angle_deg(ax) if ax is not None else 0.0)
    return bd, planar


def _fk_positions_deg(base_deg, planar_degs):
    n = len(ARM_LINK_LENGTHS)
    pd = list(planar_degs[:n])
    while len(pd) < n:
        pd.append(0.0)
    base_rad = base_deg * 0.017453292519943295
    planar_rad = [d * 0.017453292519943295 for d in pd[:n]]
    return _fk_positions_rad(base_rad, planar_rad)


def _fk_positions_rad(base_rad, planar_rads):
    """World XYZ polyline [eff0,nom0, …] — matches kinematics.forward_kinematics."""
    if not ARM_LINK_LENGTHS or len(planar_rads) != len(ARM_LINK_LENGTHS):
        return []
    cb = math.cos(base_rad)
    sb = math.sin(base_rad)
    r_hat = [cb, sb, 0.0]
    z_hat = [0.0, 0.0, 1.0]
    y_hat = [-sb, cb, 0.0]
    attach = [0.0, 0.0, ARM_BASE_VERTICAL_OFFSET]
    cumulative = 0.0
    positions = []
    for i, length in enumerate(ARM_LINK_LENGTHS):
        lx = ARM_JOINT_LATERAL_X[i] if i < len(ARM_JOINT_LATERAL_X) else 0.0
        ly = ARM_JOINT_LATERAL_Y[i] if i < len(ARM_JOINT_LATERAL_Y) else 0.0
        sin_pre = math.sin(cumulative)
        cos_pre = math.cos(cumulative)
        eff_start = [attach[0], attach[1], attach[2]]
        if lx:
            eff_start[0] += lx * (cos_pre * r_hat[0] - sin_pre * z_hat[0])
            eff_start[1] += lx * (cos_pre * r_hat[1] - sin_pre * z_hat[1])
            eff_start[2] += lx * (cos_pre * r_hat[2] - sin_pre * z_hat[2])
        if ly:
            eff_start[0] += ly * y_hat[0]
            eff_start[1] += ly * y_hat[1]
            eff_start[2] += ly * y_hat[2]
        positions.append(tuple(eff_start))

        cumulative += planar_rads[i]
        sin_c = math.sin(cumulative)
        cos_c = math.cos(cumulative)
        po = ARM_JOINT_PLANE_OFFSETS[i] if i < len(ARM_JOINT_PLANE_OFFSETS) else 0.0
        nom_end = [
            eff_start[0] + length * sin_c * r_hat[0] + (length * cos_c + po) * z_hat[0],
            eff_start[1] + length * sin_c * r_hat[1] + (length * cos_c + po) * z_hat[1],
            eff_start[2] + length * sin_c * r_hat[2] + (length * cos_c + po) * z_hat[2],
        ]
        positions.append(tuple(nom_end))
        attach = nom_end
    return positions


def _solve_2r_rad(L1, L2, r, z, elbow_down):
    """2R IK in (r,z); elbow_down ⇔ ELBOW_DOWN in kinematics.py (sin_b negative)."""
    d_sq = r * r + z * z
    d = math.sqrt(d_sq)
    if d > L1 + L2 + 1e-8 or d < abs(L1 - L2) - 1e-8:
        return None
    c_b = _clamp_scalar((d_sq - L1 * L1 - L2 * L2) / (2.0 * L1 * L2), -1.0, 1.0)
    sin_b_abs = math.sqrt(max(0.0, 1.0 - c_b * c_b))
    sin_b = -sin_b_abs if elbow_down else sin_b_abs
    theta_b = math.atan2(sin_b, c_b)
    theta_a = math.atan2(r, z) - math.atan2(L2 * sin_b, L1 + L2 * c_b)
    return (theta_a, theta_b)


def _ik_try_world(tx, ty, tz):
    """Return (base_deg, planar_degs) or None — analytical only; lateral offsets → None."""
    if any(ARM_JOINT_LATERAL_X) or any(ARM_JOINT_LATERAL_Y):
        return None
    N = len(ARM_LINK_LENGTHS)
    if N == 0:
        return None
    links = ARM_LINK_LENGTHS
    base_rad = math.atan2(ty, tx) if (abs(tx) > 1e-10 or abs(ty) > 1e-10) else 0.0
    r = math.sqrt(tx * tx + ty * ty)
    z_off = ARM_BASE_VERTICAL_OFFSET + sum(ARM_JOINT_PLANE_OFFSETS)
    z = tz - z_off
    elbow_down = IK_USE_ELBOW_DOWN

    def finish(plan_rads):
        out_deg = []
        for i, pr in enumerate(plan_rads):
            if i < len(ARM_JOINT_LIMITS_RAD):
                lo, hi = ARM_JOINT_LIMITS_RAD[i]
                pr = _clamp_scalar(pr, lo, hi)
            out_deg.append(pr * 57.29577951308232)
        return (base_rad * 57.29577951308232, out_deg)

    if N == 1:
        d = math.sqrt(r * r + z * z)
        if abs(d - links[0]) > 1e-2:
            return None
        return finish([math.atan2(r, z)])

    if N == 2:
        sol = _solve_2r_rad(links[0], links[1], r, z, elbow_down)
        if sol is None:
            return None
        return finish([sol[0], sol[1]])

    phi = math.atan2(r, z)
    tail = sum(links[2:])
    r_w = r - tail * math.sin(phi)
    z_w = z - tail * math.cos(phi)
    sol = _solve_2r_rad(links[0], links[1], r_w, z_w, elbow_down)
    if sol is None:
        return None
    ta, tb = sol
    cum = ta + tb
    plan = [ta, tb, phi - cum]
    for _ in range(N - 3):
        plan.append(0.0)
    return finish(plan[:N])


def _apply_web_command(item, axes):
    if item[0] == "JJ":
        jn = int(item[1])
        ddeg = float(item[2])
        for ax in axes:
            if ax.idx == jn:
                ax.set_target_angle(_axis_angle_deg(ax) + ddeg)
                return
    elif item[0] == "JE":
        dx = float(item[1])
        dy = float(item[2]) if len(item) > 2 else 0.0
        dz = float(item[3]) if len(item) > 3 else 0.0
        bd, pd = _angles_deg_bundle(axes)
        pos = _fk_positions_deg(bd, pd)
        if not pos:
            return
        ee = pos[-1]
        sol = _ik_try_world(ee[0] + dx, ee[1] + dy, ee[2] + dz)
        if sol is None:
            return
        base_deg, planar_deg = sol
        by_idx = {a.idx: a for a in axes}
        if 0 in by_idx:
            by_idx[0].set_target_angle(base_deg)
        for i, pdeg in enumerate(planar_deg):
            ji = i + 1
            if ji in by_idx:
                by_idx[ji].set_target_angle(pdeg)


def _web_http_server_thread(sta_ip):
    """HTTP dashboard on WEB_HTTP_PORT (STA mode only).

    ``sta_ip`` is the WLAN IPv4 from ``ifconfig()``; binding that address first
    avoids some lwIP/CYW43 setups where ``0.0.0.0`` never accepts LAN clients.
    """
    global _http_axes_ref
    try:
        import json
        import socket

        port = int(WEB_HTTP_PORT)
        candidates = []
        if sta_ip and sta_ip != "0.0.0.0":
            candidates.append((sta_ip, port))
        candidates.extend([("0.0.0.0", port), ("", port)])

        srv = None
        bound_addr = None
        last_be = None
        for addr in candidates:
            sock = None
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                sock.bind(addr)
                srv = sock
                sock = None
                bound_addr = addr
                break
            except OSError as be:
                last_be = be
                if sock is not None:
                    try:
                        sock.close()
                    except Exception:
                        pass

        if srv is None:
            raise OSError("HTTP bind failed: {}".format(last_be))

        srv.listen(4)
        srv.settimeout(1.0)
        _show_ip = bound_addr[0] if bound_addr and bound_addr[0] else "0.0.0.0"
        print("HTTP dashboard listening on {}:{}".format(_show_ip, port))
        _flush_stdout()

        html = """<!DOCTYPE html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Arm dashboard</title><style>
body{font-family:system-ui,sans-serif;background:#111;color:#eee;margin:0;padding:12px;}
h1{font-size:1.1rem;margin:0 0 8px;}
.row{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:10px;align-items:center;}
.dot{width:14px;height:14px;border-radius:50%;display:inline-block;margin-right:6px;vertical-align:middle;}
.dot.on{background:#0f0;box-shadow:0 0 6px #0f0;}.dot.off{background:#644;}.dot.na{background:#333;}
svg{background:#1a1a1a;border:1px solid #333;display:block;max-width:100%;}button{margin:2px;padding:6px 10px;cursor:pointer;touch-action:manipulation;-webkit-user-select:none;user-select:none;}
.ee{font-family:monospace;font-size:14px;}small{color:#888;}
.hdr{margin:10px 0 4px;color:#aaa;font-size:11px;}
</style></head><body>
<h1>Pico arm dashboard</h1>
<p><small>TCP """ + str(TCP_PORT) + """ · HTTP """ + str(WEB_HTTP_PORT) + """</small></p>
<div class="row" id="sw"></div>
<svg id="sv" width="320" height="240" viewBox="-110 -110 220 220"><path id="armPath" stroke="#6cf" stroke-width="3" fill="none" d=""/></svg>
<p class="ee" id="ee"></p>
<p class="hdr">End-effector jog — world XYZ (mm, hold)</p>
<div class="row">
<button type="button" id="exm">EE −X</button><button type="button" id="exp">EE +X</button>
<button type="button" id="eym">EE −Y</button><button type="button" id="eyp">EE +Y</button>
<button type="button" id="ezm">EE −Z</button><button type="button" id="ezp">EE +Z</button>
</div>
<p class="hdr">Joint jog — degrees (hold)</p>
<div class="row" id="jb"></div>
<script>
function armLine(points){if(points.length<2)return '';
let mx=0,my=0,Mx=0,My=0;for(const p of points){mx=Math.min(mx,p[0]);Mx=Math.max(Mx,p[0]);my=Math.min(my,p[1]);My=Math.max(My,p[1]);}
const rw=Math.max(Mx-mx,1e-6),rh=Math.max(My-my,1e-6),sc=Math.min(180/rw,180/rh)*0.85,cx=(mx+Mx)/2,cy=(my+My)/2;
let d='';for(let i=0;i<points.length;i++){const x=(points[i][0]-cx)*sc,y=-(points[i][1]-cy)*sc;d+=(i?'L':'M')+x+','+y;}
return d;}
var jbBuiltSig='',swBuiltSig='',holdIv=null,holdUrl=null;
var stateBusy=false,statePending=false;
function rebuildSwitches(swArr){var el=document.getElementById('sw'),h='';for(var i=0;i<swArr.length;i++){h+='<span><span class="dot na"></span>J'+swArr[i].idx+' limit</span> ';}el.innerHTML=h.trimEnd();}
function updateSwitchDots(swArr){var el=document.getElementById('sw');for(var i=0;i<swArr.length;i++){var span=el.children[i];if(!span)return false;var dot=span.querySelector('.dot');if(!dot)return false;var s=swArr[i];dot.className='dot '+(s.pressed?'on':(s.wired?'off':'na'));}return true;}
function rebuildJointButtons(joints){var el=document.getElementById('jb');el.innerHTML='';for(var i=0;i<joints.length;i++){var jo=joints[i];var bm=document.createElement('button');bm.type='button';bm.textContent='J'+jo.idx+' −';bindHold(bm,'/api/jog_joint?j='+jo.idx+'&delta=-0.5');el.appendChild(bm);var bp=document.createElement('button');bp.type='button';bp.textContent='J'+jo.idx+' +';bindHold(bp,'/api/jog_joint?j='+jo.idx+'&delta=0.5');el.appendChild(bp);el.appendChild(document.createTextNode(' '));}}
async function refreshState(){
if(stateBusy){statePending=true;return;}
stateBusy=true;
try{
var r=await fetch('/api/state',{cache:'no-store'});
var j=await r.json();
document.getElementById('ee').textContent='EE X='+j.ee.x+' Y='+j.ee.y+' Z='+j.ee.z+(j.fk_ok?'':' (FK off)');
var swSig=j.switches.map(function(s){return s.idx;}).join('|');
if(swSig!==swBuiltSig){rebuildSwitches(j.switches);swBuiltSig=swSig;}else if(!updateSwitchDots(j.switches)){rebuildSwitches(j.switches);}
var jbSig=j.joints.map(function(x){return x.idx;}).join('|');
if(jbSig!==jbBuiltSig){rebuildJointButtons(j.joints);jbBuiltSig=jbSig;}
var pts=j.polyline_xy||[];document.getElementById('armPath').setAttribute('d',pts.length?armLine(pts):'');
}catch(e){console.warn(e);}
finally{
stateBusy=false;
if(statePending){statePending=false;refreshState();}
}
}
async function pollLoop(){
while(true){
try{await refreshState();await new Promise(function(r){setTimeout(r,14);});}
catch(e){console.warn(e);await new Promise(function(r){setTimeout(r,80);});}
}
}
pollLoop();
function stopHold(){if(holdIv){clearInterval(holdIv);holdIv=null;}holdUrl=null;}
function fireHold(){
if(!holdUrl)return;
fetch(holdUrl,{cache:'no-store',keepalive:true}).then(function(){refreshState();}).catch(function(){});
}
function startHold(url){stopHold();holdUrl=url;fireHold();holdIv=setInterval(fireHold,28);}
function bindHold(el,url){
el.addEventListener('pointerdown',function(e){if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();try{el.setPointerCapture(e.pointerId);}catch(x){}startHold(url);});
el.addEventListener('pointerup',stopHold);el.addEventListener('pointercancel',stopHold);el.addEventListener('lostpointercapture',stopHold);}
bindHold(document.getElementById('exm'),'/api/jog_ee?dx=-0.35');
bindHold(document.getElementById('exp'),'/api/jog_ee?dx=0.35');
bindHold(document.getElementById('eym'),'/api/jog_ee?dy=-0.35');
bindHold(document.getElementById('eyp'),'/api/jog_ee?dy=0.35');
bindHold(document.getElementById('ezm'),'/api/jog_ee?dz=-0.35');
bindHold(document.getElementById('ezp'),'/api/jog_ee?dz=0.35');
window.addEventListener('blur',stopHold);
window.addEventListener('pointerup',stopHold);
</script>
</body></html>"""

        while True:
            try:
                conn, _addr = srv.accept()
            except OSError:
                continue
            try:
                conn.settimeout(3.0)
                req = b""
                while b"\r\n\r\n" not in req and len(req) < 4096:
                    req += conn.recv(512)
                if not req:
                    conn.close()
                    continue
                head = req.split(b"\r\n\r\n", 1)[0].decode("utf-8", "replace")
                lines = head.split("\r\n")
                req_line = lines[0] if lines else ""
                parts = req_line.split()
                path_full = parts[1] if len(parts) > 1 else "/"
                path = path_full
                qs = ""
                if "?" in path_full:
                    path, qs = path_full.split("?", 1)

                if path == "/" or path == "/index.html":
                    body = html
                    ctype = "text/html; charset=utf-8"
                elif path == "/api/state":
                    axes = _http_axes_ref
                    bd, pd = _angles_deg_bundle(axes) if axes else (0.0, [])
                    pts3 = _fk_positions_deg(bd, pd) if axes else []
                    fk_ok = len(pts3) > 0
                    poly_xy = [[round(p[0], 4), round(p[1], 4)] for p in pts3] if fk_ok else []
                    joints_out = []
                    sw_out = []
                    for ax in sorted(axes or [], key=lambda a: a.idx):
                        live = False
                        if getattr(ax, "_home_pin", None) is not None:
                            try:
                                pv = ax._home_pin.value()
                                live = (pv == 1) if ax.home_pin_polarity == "NC" else (pv == 0)
                            except Exception:
                                live = False
                        joints_out.append({"idx": ax.idx, "deg": round(_axis_angle_deg(ax), 3)})
                        sw_out.append({"idx": ax.idx, "pressed": live, "wired": getattr(ax, "_home_pin", None) is not None})
                    ee = pts3[-1] if fk_ok else (0.0, 0.0, 0.0)
                    doc = {
                        "fk_ok": fk_ok,
                        "joints": joints_out,
                        "switches": sw_out,
                        "ee": {
                            "x": round(ee[0], 4),
                            "y": round(ee[1], 4),
                            "z": round(ee[2], 4),
                        },
                        "polyline_xy": poly_xy,
                        "tcp_control_port": TCP_PORT,
                        "http_port": WEB_HTTP_PORT,
                    }
                    body = json.dumps(doc)
                    ctype = "application/json"
                elif path == "/api/jog_joint":
                    pr = {}
                    for pair in qs.split("&"):
                        if "=" in pair:
                            k, v = pair.split("=", 1)
                            pr[k] = v
                    try:
                        jn = int(pr.get("j", "-1"))
                        delta = float(pr.get("delta", "0"))
                        _web_cmd_queue.append(("JJ", jn, delta))
                        while len(_web_cmd_queue) > 64:
                            _web_cmd_queue.pop(0)
                        body = '{"ok":true}'
                    except Exception:
                        body = '{"ok":false}'
                    ctype = "application/json"
                elif path == "/api/jog_ee":
                    pr = {}
                    for pair in qs.split("&"):
                        if "=" in pair:
                            k, v = pair.split("=", 1)
                            pr[k] = v
                    try:
                        dx = float(pr.get("dx", "0"))
                        dy = float(pr.get("dy", "0"))
                        dz = float(pr.get("dz", "0"))
                        _web_cmd_queue.append(("JE", dx, dy, dz))
                        while len(_web_cmd_queue) > 64:
                            _web_cmd_queue.pop(0)
                        body = '{"ok":true}'
                    except Exception:
                        body = '{"ok":false}'
                    ctype = "application/json"
                else:
                    body = "Not found"
                    ctype = "text/plain"

                raw_b = body.encode("utf-8")
                hdr = (
                    "HTTP/1.0 200 OK\r\nContent-Type: "
                    + ctype
                    + "\r\nConnection: close\r\nContent-Length: "
                    + str(len(raw_b))
                    + "\r\n\r\n"
                )
                conn.send(hdr.encode("utf-8") + raw_b)
            except Exception:
                pass
            try:
                conn.close()
            except Exception:
                pass
    except Exception as exc:
        try:
            print("WARN: web dashboard:", exc)
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Unified velocity → step budget (host-follow, homing, PIO pulse spacing)
# All step-rate motion uses these limits only: max_speed_sps, accel_sps2, jerk_sps3.
# ---------------------------------------------------------------------------

AXIS_PLAN_EPS_STEPS = 0.5
HOMING_PLAN_ERR_MAG = 1e9


def axis_plan_velocity_steps(
    dt,
    signed_position_error_steps,
    vel_signed,
    frac_carry,
    dv_prev,
    max_speed_sps,
    accel_sps2,
    jerk_sps3,
    max_burst,
):
    """Plan integer full-steps this tick from accel/jerk-limited velocity toward ``signed_position_error_steps``.

    Parameters mirror motor tab units (full steps/s, s/s², s/s³). Returns:
    ``(n_steps, new_vel_signed, new_frac_carry, new_dv_prev)``.
    """
    tdt = max(dt, 1e-9)
    e = float(signed_position_error_steps)
    a = abs(e)
    if a < AXIS_PLAN_EPS_STEPS:
        return 0, 0.0, 0.0, 0.0

    ae = float(accel_sps2)
    if ae <= 0.0:
        ae = max(float(max_speed_sps) * 10.0, 400.0)

    vmax = max(float(max_speed_sps), 1e-9)
    ds = max(0.0, a - 0.5)
    v_cap_k = math.sqrt(max(0.0, 2.0 * ae * ds))
    v_cap = min(vmax, v_cap_k)
    v_cmd = math.copysign(v_cap, e)

    dv_max = ae * tdt
    diff = v_cmd - vel_signed
    if diff > dv_max:
        dv_raw = dv_max
    elif diff < -dv_max:
        dv_raw = -dv_max
    else:
        dv_raw = diff

    jk = float(jerk_sps3)
    if jk > 0.0:
        lim = jk * tdt * tdt
        if dv_raw > dv_prev + lim:
            dv_raw = dv_prev + lim
        elif dv_raw < dv_prev - lim:
            dv_raw = dv_prev - lim
        ndv_prev = dv_raw
    else:
        ndv_prev = dv_raw

    vel_signed = vel_signed + dv_raw
    spd = abs(vel_signed)
    if spd < 1e-9:
        return 0, vel_signed, frac_carry, ndv_prev

    frac_carry += spd * tdt
    n_rate = int(frac_carry)
    frac_carry -= float(n_rate)
    n_rate = min(n_rate, int(max_burst))
    n_want = int(min(a + 0.5, 1e7))
    return min(n_want, n_rate), vel_signed, frac_carry, ndv_prev


# ---------------------------------------------------------------------------
# Stepper axis base class
# ---------------------------------------------------------------------------

class _StepperBase:
    """Host trajectory → steps; motion uses :func:`axis_plan_velocity_steps` only.

    Limits are ``max_sps``, ``accel``, ``jerk`` from ``JOINTS`` (plus optional homing speed cap).
    """

    def __init__(self, cfg: dict):
        self.idx            = cfg["idx"]
        self.steps_per_rev  = cfg["steps_per_rev"]
        self.gear_ratio     = cfg.get("gear_ratio", 1.0)
        # Safety cap on how many full steps to emit in one main-loop tick
        self.max_sps        = cfg["max_sps"]
        _ac = float(cfg.get("accel", 0))
        # Steps/s² — if missing/0, default ~0.1 s to reach max_sps for smooth ramps
        self.accel = _ac if _ac > 0.0 else max(float(self.max_sps) * 10.0, 400.0)
        self.jerk = float(cfg.get("jerk", 0))  # steps/s³ — limits |Δ(dv)| per tick when > 0
        self.zero_offset    = cfg.get("zero_offset_deg", 0.0)
        # Kept in JOINTS for PC-side direction-reversal compensation; not used on-device
        self.backlash_steps = int(cfg.get("backlash_steps", 0))
        # Output steps per one full output revolution
        self._steps_out = self.steps_per_rev * self.gear_ratio

        # Motion state
        self.current_pos: float = 0.0   # steps (logical position — not counting backlash)
        self.target_pos:  float = 0.0
        self.velocity:    float = 0.0   # debug: last-tick step rate, signed
        self._last_dir: int = 0         # last physical step direction (+1 fwd, -1 bwd)
        self._steps_since_report: int = 0  # physical steps taken since last pin_debug call
        self._steps_last_tick: int = 0

        # Home/limit switch support (optional, can be used by both 28BYJ and StepDir)
        home_pin_num = cfg.get("home_pin")
        self.home_pin_num = home_pin_num   # stored for diagnostics / HOMEJ reply
        if home_pin_num is not None:
            self._home_pin = Pin(home_pin_num, Pin.IN, pull=Pin.PULL_UP)
            self.home_pin_polarity = cfg.get("home_pin_polarity", "NO")  # "NO"=active-high, "NC"=active-low
        else:
            self._home_pin = None
            self.home_pin_polarity = "NO"
        self.home_direction = cfg.get("home_direction", 1)  # +1 or -1 to seek home
        # Fine speed: backup, precision; search speed: first run toward switch (both from JOINTS / deploy)
        _hs = float(cfg.get("home_speed_sps", 100))
        self.home_speed_sps = _hs
        self.home_search_speed_sps = float(cfg.get("home_search_speed_sps", _hs))
        self.home_backup_steps = float(max(1.0, float(cfg.get("home_backup_steps", 5.0))))
        self.home_offset_deg = cfg.get("home_offset_deg", 0.0)  # move this far after touching off
        self.at_home = False  # state flag: True when home switch is active
        self._homing_mode = False  # flag: currently in homing sequence
        self._homing_stage = "approach"  # stage: approach, backup, precision
        self._homing_backup_start = 0.0  # current_pos when backup began
        self._homing_backup_distance = 0.0  # how many steps to back off
        self._homing_last_stage: str = ""
        # Shared velocity planner state (axis_plan_velocity_steps): host-follow + homing use same integrators
        self._host_sps_accum: float = 0.0   # legacy SYNC clear; kept for compatibility
        self._host_follow_vel: float = 0.0  # signed steps/s toward +target
        self._host_follow_frac: float = 0.0  # fractional step carry
        self._host_dv_prev: float = 0.0  # last velocity increment (for jerk limiting)

        # Software travel limits (None = disabled)
        _lmin = cfg.get("limit_min_deg")
        _lmax = cfg.get("limit_max_deg")
        self._limit_min = (_lmin / 360.0 * self._steps_out) if _lmin is not None else None
        self._limit_max = (_lmax / 360.0 * self._steps_out) if _lmax is not None else None

    def angle_to_steps(self, angle_deg: float) -> float:
        return (angle_deg - self.zero_offset) / 360.0 * self._steps_out

    def set_target_angle(self, angle_deg: float) -> None:
        # During homing the state machine sets target_pos directly — ignore
        # incoming PC commands so they don't overwrite the homing target.
        if self._homing_mode:
            return
        new_pos = self.angle_to_steps(angle_deg)
        # Enforce software travel limits at the command level.
        if self._limit_min is not None:
            new_pos = max(new_pos, self._limit_min)
        if self._limit_max is not None:
            new_pos = min(new_pos, self._limit_max)
        self.target_pos = new_pos

    def deenergise(self) -> None:
        """Override in drivers that can cut hold current. Default: no-op."""
        pass

    def clear_host_follow_rates(self) -> None:
        """Zero unified motion-plan integrators (STOP, SYNC, homing stage changes)."""
        self._host_sps_accum = 0.0
        self._host_follow_vel = 0.0
        self._host_follow_frac = 0.0
        self._host_dv_prev = 0.0

    def _homing_step_budget(self, speed_sps, dt, step_sign) -> int:
        """Steps this tick toward open-loop homing direction using same planner as host-follow."""
        n, self._host_follow_vel, self._host_follow_frac, self._host_dv_prev = axis_plan_velocity_steps(
            dt,
            HOMING_PLAN_ERR_MAG * float(step_sign),
            self._host_follow_vel,
            self._host_follow_frac,
            self._host_dv_prev,
            float(speed_sps),
            float(self.accel),
            float(self.jerk),
            MAX_STEPS_PER_AXIS_TICK,
        )
        if _HOMING_ONE_STEP_PER_TICK:
            return min(n, 1)
        return n

    def _emit_one_step(self, forward) -> None:
        # Backlash is applied on the PC to commanded angles on direction change; here
        # logical position always follows each physical step.
        if forward:
            self.current_pos += 1.0
            self._step(1, forward=True)
            self._last_dir = 1
        else:
            self.current_pos -= 1.0
            self._step(1, forward=False)
            self._last_dir = -1
        self._steps_since_report += 1

    def _emit_n_in_direction(self, n_cap, forward) -> int:
        n = 0
        for _ in range(n_cap):
            self._emit_one_step(forward)
            n += 1
        return n

    def _emit_n_toward_target(self, n_cap) -> int:
        n = 0
        for _ in range(n_cap):
            e = self.target_pos - self.current_pos
            if abs(e) < 0.5:
                break
            self._emit_one_step(e > 0.0)
            n += 1
        return n

    def _host_follow_budget(self, dt) -> int:
        """Steps toward ``target_pos`` using :func:`axis_plan_velocity_steps` (``max_sps``, ``accel``, ``jerk``)."""
        e = self.target_pos - self.current_pos
        n, self._host_follow_vel, self._host_follow_frac, self._host_dv_prev = axis_plan_velocity_steps(
            dt,
            e,
            self._host_follow_vel,
            self._host_follow_frac,
            self._host_dv_prev,
            float(self.max_sps),
            float(self.accel),
            float(self.jerk),
            MAX_STEPS_PER_AXIS_TICK,
        )
        if n == 0 and abs(e) < AXIS_PLAN_EPS_STEPS:
            self._host_sps_accum = 0.0
        return n

    def _interleave_plan_host_steps(self, tdt) -> int:
        """Plan host-follow for this tick (called from main when _HOST_INTERLEAVE_STEPS).

        Returns -1 if the axis should not emit (at home switch, or still in homing — caller bug).
        Otherwise sets _interleave_e0 / _interleave_left and returns the planned step count.
        """
        tdt = max(tdt, 1e-9)
        if self._homing_mode:
            self._interleave_left = 0
            if hasattr(self, "_interleave_e0"):
                del self._interleave_e0
            return -1
        if self._home_pin is not None:
            pin_state = self._home_pin.value()
            home_active = (pin_state == 1) if self.home_pin_polarity == "NC" else (pin_state == 0)
            if home_active:
                self.at_home = True
                if (self.target_pos - self.current_pos) * self.home_direction > 0:
                    self.target_pos = self.current_pos
                self.velocity = 0.0
                self._interleave_left = 0
                if hasattr(self, "_interleave_e0"):
                    del self._interleave_e0
                return -1
            self.at_home = False
        if self._limit_min is not None and self.current_pos <= self._limit_min:
            self.target_pos = max(self.target_pos, self._limit_min)
        if self._limit_max is not None and self.current_pos >= self._limit_max:
            self.target_pos = min(self.target_pos, self._limit_max)
        self._interleave_e0 = self.target_pos - self.current_pos
        n = self._host_follow_budget(tdt)
        self._interleave_left = n
        return n

    def _finalize_interleave_host(self, tdt) -> None:
        """Update velocity debug after interleaved emits for this tick."""
        tdt = max(tdt, 1e-9)
        if not hasattr(self, "_interleave_e0"):
            return
        e_after = self.target_pos - self.current_pos
        de = self._interleave_e0 - e_after
        if abs(de) < 1e-9:
            self.velocity = 0.0
        else:
            self.velocity = de / tdt

    def update(self, dt: float) -> None:
        """Advance stepping toward target / homing using :func:`axis_plan_velocity_steps`."""
        tdt = max(dt, 1e-9)
        e_before = self.target_pos - self.current_pos

        if self._home_pin is not None:
            pin_state = self._home_pin.value()
            home_active = (pin_state == 1) if self.home_pin_polarity == "NC" else (pin_state == 0)

            if not self._homing_mode and home_active:
                self.at_home = True
                if (self.target_pos - self.current_pos) * self.home_direction > 0:
                    self.target_pos = self.current_pos
                self.velocity = 0.0
                return
            if not self._homing_mode:
                if not home_active:
                    self.at_home = False
            else:
                st = self._homing_stage
                if st != self._homing_last_stage:
                    self.clear_host_follow_rates()
                    self._homing_last_stage = st
                hdir = self.home_direction
                hs = self.home_speed_sps
                hsearch = self.home_search_speed_sps
                s_last = 0

                if st == "approach":
                    if home_active:
                        self._homing_stage = "backup"
                        self._homing_backup_start = self.current_pos
                        self._homing_backup_distance = self.home_backup_steps
                        f_back = (hs * -hdir) > 0
                        n_b = self._homing_step_budget(hs, dt, 1 if f_back else -1)
                        s_last = self._emit_n_in_direction(n_b, f_back)
                    else:
                        f = (hsearch * hdir) > 0
                        n_search = self._homing_step_budget(hsearch, dt, 1 if f else -1)
                        s_last = self._emit_n_in_direction(n_search, f)
                elif st == "backup":
                    backed = abs(self.current_pos - self._homing_backup_start)
                    if backed >= self._homing_backup_distance and not home_active:
                        self._homing_stage = "precision"
                    else:
                        f = (hs * -hdir) > 0
                        n_slow = self._homing_step_budget(hs, dt, 1 if f else -1)
                        s_last = self._emit_n_in_direction(n_slow, f)
                elif st == "precision":
                    if home_active:
                        self.current_pos = 0.0
                        offset_steps = self.home_offset_deg / 360.0 * self._steps_out
                        if abs(offset_steps) > 0.5:
                            self.target_pos = -hdir * abs(offset_steps)
                            self.clear_host_follow_rates()
                            self._homing_stage = "offset"
                        else:
                            self.at_home = True
                            self._homing_mode = False
                            self._homing_stage = "approach"
                            self.clear_host_follow_rates()
                            self._homing_last_stage = ""
                    else:
                        f = (hs * hdir) > 0
                        n_slow = self._homing_step_budget(hs, dt, 1 if f else -1)
                        s_last = self._emit_n_in_direction(n_slow, f)
                elif st == "offset":
                    s_last = self._emit_n_toward_target(self._host_follow_budget(tdt))
                    if abs(self.current_pos - self.target_pos) < 0.5:
                        self.current_pos = 0.0
                        self.target_pos = 0.0
                        self.at_home = True
                        self._homing_mode = False
                        self._homing_stage = "approach"
                        self.clear_host_follow_rates()
                        self._homing_last_stage = ""

                sgn = 1.0 if self._last_dir == 1 else -1.0
                if s_last:
                    self.velocity = (s_last / tdt) * sgn
                else:
                    self.velocity = 0.0
                return

        if _HOST_INTERLEAVE_STEPS:
            # Host follow (limits + stepping) runs in main() round-robin with other axes.
            return

        if not self._homing_mode:
            if self._limit_min is not None and self.current_pos <= self._limit_min:
                self.target_pos = max(self.target_pos, self._limit_min)
            if self._limit_max is not None and self.current_pos >= self._limit_max:
                self.target_pos = min(self.target_pos, self._limit_max)

        n = self._emit_n_toward_target(self._host_follow_budget(tdt))
        e_after = self.target_pos - self.current_pos
        if n == 0:
            self.velocity = 0.0
        else:
            self.velocity = (e_before - e_after) / tdt

    def _step(self, count: int, forward: bool) -> None:
        raise NotImplementedError


# ---------------------------------------------------------------------------
# 28BYJ-48 axis (IN1 IN2 IN3 IN4 half-step sequence)
# ---------------------------------------------------------------------------

class StepperAxis28BYJ(_StepperBase):
    """28BYJ-48 with ULN2003 driver — 4-pin half-step sequencing."""

    def __init__(self, cfg: dict):
        super().__init__(cfg)
        pins = cfg["pins"]   # [IN1, IN2, IN3, IN4]
        if len(pins) != 4:
            raise ValueError(f"28byj driver needs 4 pins, got {pins}")
        self._pin_nums = pins
        self._pins = [Pin(p, Pin.OUT, value=0) for p in pins]
        self._seq_idx = 0    # current position in _HALFSTEP table

    def _step(self, count: int, forward: bool) -> None:
        step_dir = 1 if forward else -1
        for _ in range(count):
            self._seq_idx = (self._seq_idx + step_dir) % 8
            pattern = _HALFSTEP[self._seq_idx]
            for pin, val in zip(self._pins, pattern):
                pin.value(val)
            # No sleep here — coil hold time is enforced by the main loop's
            # fixed STEP_US period, giving perfectly consistent step timing.

    def deenergise(self) -> None:
        """Cut coil current when idle to reduce heat."""
        for pin in self._pins:
            pin.value(0)

    def get_pin_debug(self) -> str:
        coils = "".join(str(p.value()) for p in self._pins)
        labels = ["IN1", "IN2", "IN3", "IN4"]
        pairs = " ".join("GP{}({})={}".format(n, lbl, p.value())
                         for n, lbl, p in zip(self._pin_nums, labels, self._pins))
        n = self._steps_since_report; self._steps_since_report = 0
        return "{} sps~{}".format(pairs, n)


# ---------------------------------------------------------------------------
# NEMA 17 (step/dir) axis
# ---------------------------------------------------------------------------

class StepperAxisStepDir(_StepperBase):
    """NEMA 17 (or any step/dir motor) via A4988 / DRV8825 / TMC2209."""

    def __init__(self, cfg: dict):
        super().__init__(cfg)
        pins = cfg["pins"]   # [STEP, DIR]
        if len(pins) < 2:
            raise ValueError(f"stepdir driver needs 2 pins, got {pins}")
        self._step_pin_num = pins[0]
        self._dir_pin_num  = pins[1]
        self._step_pin = Pin(pins[0], Pin.OUT, value=0)
        self._dir_pin  = Pin(pins[1], Pin.OUT, value=0)
        # steps_per_rev already encodes the driver dip-switch resolution (e.g. 800)
        # no microstepping multiplier needed — set steps_per_rev to match the driver
        self.invert_dir    = cfg.get("invert_dir", False)
        # Hold DIR stable before toggling STEP (many A4988/DRV boards need 5–20+ µs)
        self.dir_setup_us  = int(cfg.get("dir_setup_us", 12))
        self._last_phys_dir: int = -1   # sentinel — unknown until first step

    def _step(self, count: int, forward: bool) -> None:
        physical_forward = (not forward) if self.invert_dir else forward
        phys_dir = 1 if physical_forward else 0
        self._dir_pin.value(phys_dir)
        if phys_dir != self._last_phys_dir and self.dir_setup_us > 0:
            time.sleep_us(self.dir_setup_us)
        self._last_phys_dir = phys_dir
        # ≥2.5 µs is typical for opto inputs (e.g. DM542); use 3 µs for margin.
        for _ in range(count):
            self._step_pin.value(1)
            time.sleep_us(3)
            self._step_pin.value(0)
            time.sleep_us(3)

    def deenergise(self) -> None:
        """STEP/DIR breakouts: no separate coil pins to cut (unlike 28BYJ).

        We leave STEP low; the driver + motor may still hold torque if ENABLE
        is tied. Optional enable GPIO could be added to config later to disable
        the driver.
        """
        self._step_pin.value(0)

    def get_pin_debug(self) -> str:
        n = self._steps_since_report; self._steps_since_report = 0
        return "GP{}(STEP)=0* GP{}(DIR)={} sps~{}".format(
            self._step_pin_num, self._dir_pin_num,
            self._dir_pin.value(), n
        )


# ---------------------------------------------------------------------------
# NEMA step/dir via PIO (hardware-timed STEP); DIR still from CPU
# ---------------------------------------------------------------------------


class StepperAxisStepDirPIO(_StepperBase):
    """STEP/DIR with STEP generated by PIO for stable pulse spacing."""

    def __init__(self, cfg: dict):
        if not _PIO_HAVE_STEP:
            raise RuntimeError("PIO not available")
        super().__init__(cfg)
        pins = cfg["pins"]
        if len(pins) < 2:
            raise ValueError(f"stepdir PIO needs 2 pins, got {pins}")
        self._step_pin_num = pins[0]
        self._dir_pin_num = pins[1]
        self._dir_pin = Pin(pins[1], Pin.OUT, value=0)
        self.invert_dir = cfg.get("invert_dir", False)
        self.dir_setup_us = int(cfg.get("dir_setup_us", 12))
        self._last_phys_dir: int = -1
        self._pio_fc = float(machine.freq())
        sm_id = _pio_alloc_sm_id(cfg)
        self._sm = StateMachine(
            sm_id,
            _pio_step_pulse_program,
            freq=int(self._pio_fc),
            set_base=Pin(pins[0]),
        )
        self._sm.active(1)

    def _step(self, count: int, forward: bool) -> None:
        try:
            self._sm.active(1)
        except Exception:
            pass
        physical_forward = (not forward) if self.invert_dir else forward
        phys_dir = 1 if physical_forward else 0
        self._dir_pin.value(phys_dir)
        if phys_dir != self._last_phys_dir and self.dir_setup_us > 0:
            time.sleep_us(self.dir_setup_us)
        self._last_phys_dir = phys_dir
        period = max(
            64,
            min(
                0x7FFFFFFF,
                int(
                    self._pio_fc
                    / max(1.0, 2.0 * max(1.0, abs(self._host_follow_vel)))
                ),
            ),
        )
        for _ in range(count):
            self._sm.put(period)

    def deenergise(self) -> None:
        try:
            self._sm.active(0)
        except Exception:
            pass
        Pin(self._step_pin_num, Pin.OUT, value=0)

    def get_pin_debug(self) -> str:
        n = self._steps_since_report; self._steps_since_report = 0
        return "GP{}(STEP)=PIO GP{}(DIR)={} sps~{}".format(
            self._step_pin_num, self._dir_pin_num,
            self._dir_pin.value(), n
        )


# ---------------------------------------------------------------------------
# RC servo axis (PWM — single signal pin)
# ---------------------------------------------------------------------------

class ServoAxis:
    """Standard RC servo controlled via 50 Hz PWM.

    Angle maps linearly between min_pulse_us (0°) and max_pulse_us (angle_range_deg°).
    The servo moves to the target position immediately on set_target_angle() —
    no velocity profile needed; the servo's internal controller handles motion.

    Wiring: SIG → GPIO pin.  VCC → VBUS (5 V) or separate supply.
            ALWAYS share GND between Pico and the servo supply.
    """

    def __init__(self, cfg: dict):
        self.idx            = cfg["idx"]
        self.zero_offset    = cfg.get("zero_offset_deg", 0.0)
        self.min_pulse_us   = cfg.get("min_pulse_us", 1000)
        self.max_pulse_us   = cfg.get("max_pulse_us", 2000)
        self.angle_range    = cfg.get("angle_range_deg", 180)
        self.velocity       = 0.0   # always 0 — servo has built-in position control
        # Shared interface required by the main loop (STOP command, etc.)
        self.current_pos    = 0.0
        self.target_pos     = 0.0
        self._homing_mode   = False
        self._homing_stage  = "approach"
        self._accumulator   = 0.0
        self._accel_now     = 0.0
        self._home_pin      = None  # servos don't have limit switches

        pins = cfg.get("pins", [])
        if not pins:
            raise ValueError(f"servo joint {cfg.get('idx')} needs at least 1 pin")
        self._pin_num = pins[0]
        self._pwm = PWM(Pin(self._pin_num))
        self._pwm.freq(50)   # standard 50 Hz servo signal

    def set_target_angle(self, angle_deg: float) -> None:
        """Move servo to angle_deg immediately.

        Simulator joint angles are centered at 0° (negative = one direction,
        positive = other).  The servo range starts at 0°, so we shift by
        half the range: simulator 0° → servo midpoint → centre pulse width.

        Example (180° range, 1000–2000 µs):
            sim  0° → servo  90° → 1500 µs  (centre)
            sim +90° → servo 180° → 2000 µs (max)
            sim -90° → servo   0° → 1000 µs (min)
        """
        self.target_pos = angle_deg - self.zero_offset
        angle = angle_deg - self.zero_offset
        # Shift so simulator 0° maps to the servo's midpoint
        servo_angle = angle + self.angle_range / 2.0
        servo_angle = max(0.0, min(self.angle_range, servo_angle))
        pulse_us = self.min_pulse_us + (servo_angle / max(self.angle_range, 1)) * (
            self.max_pulse_us - self.min_pulse_us
        )
        # duty_u16 range: 0–65535 = 0–100% of 20 ms period
        duty = int((pulse_us / 20000.0) * 65535)
        self._pwm.duty_u16(max(0, min(65535, duty)))

    def update(self, dt: float) -> None:
        pass   # servo handles its own motion — nothing to do each tick

    def deenergise(self) -> None:
        pass   # servos hold position without coil heating — nothing to cut

    def get_pin_debug(self) -> str:
        return "GP{}(SIG)=PWM".format(self._pin_num if hasattr(self, "_pin_num") else "?")


# ---------------------------------------------------------------------------
# Factory & diagnostics
# ---------------------------------------------------------------------------

def _axis_wiring_line(ax) -> str:
    """How this axis is wired (STEP/DIR vs 28BYJ coils). Shown at boot and for STEPT/PRINTAXES."""
    cls = type(ax).__name__
    if cls == "StepperAxisStepDir":
        return "J{0} STEP=GP{1} DIR=GP{2} ({3})".format(
            ax.idx, ax._step_pin_num, ax._dir_pin_num, cls
        )
    if cls == "StepperAxisStepDirPIO":
        return "J{0} STEP=GP{1}(PIO) DIR=GP{2} ({3})".format(
            ax.idx, ax._step_pin_num, ax._dir_pin_num, cls
        )
    if cls == "StepperAxis28BYJ":
        return "J{0} ULN IN1..4 = GP{1} ({2})".format(ax.idx, ax._pin_nums, cls)
    if cls == "ServoAxis":
        return "J{0} Servo (PWM) ({1})".format(ax.idx, cls)
    return "J{0} ({1})".format(ax.idx, cls)


def make_axis(cfg: dict):
    driver = cfg.get("driver", "stepdir").lower()
    if driver == "28byj":
        return StepperAxis28BYJ(cfg)
    elif driver == "stepdir":
        use_pio = cfg.get("pio_stepdir", True)
        if use_pio:
            if not _PIO_HAVE_STEP:
                raise RuntimeError(
                    "stepdir needs PIO for STEP (rp2/asm_pio unavailable); "
                    "set pio_stepdir false for GPIO STEP debug only"
                )
            return StepperAxisStepDirPIO(cfg)
        return StepperAxisStepDir(cfg)
    elif driver == "servo":
        return ServoAxis(cfg)
    else:
        raise ValueError(f"Unknown driver type '{driver}' for joint {cfg.get('idx')}")


def _apply_host_follow_sps_cap(axes) -> None:
    """When HOST_FOLLOW_MAX_SPS > 0, scale all stepper max_sps by min(1, cap/peak_configured)."""
    try:
        cap = int(HOST_FOLLOW_MAX_SPS)
    except Exception:
        return
    if cap <= 0:
        return
    steppers = [ax for ax in axes if hasattr(ax, "max_sps")]
    if not steppers:
        return
    peak = 0.0
    for ax in steppers:
        m = float(ax.max_sps)
        if m > peak:
            peak = m
    if peak <= 0:
        return
    scale = float(cap) / peak
    if scale >= 1.0:
        return
    for ax in steppers:
        ax.max_sps = int(round(float(ax.max_sps) * scale))
        ax.accel = float(ax.accel) * scale


# ---------------------------------------------------------------------------
# Host trajectory ring buffer (``T:`` timestamped joint samples)
# ---------------------------------------------------------------------------


class TrajectoryRing:
    """Rolling buffer of (stream_time_s, pose_deg_tuple) for interpolation."""

    def __init__(self):
        self._times = []
        self._poses = []

    def clear(self):
        self._times.clear()
        self._poses.clear()

    def empty(self):
        return len(self._times) == 0

    def push(self, t_s, pose_deg):
        if self._times and t_s <= self._times[-1]:
            self._times.pop()
            self._poses.pop()
        self._times.append(float(t_s))
        self._poses.append(pose_deg)
        while len(self._times) > TRAJ_RING_CAP:
            self._times.pop(0)
            self._poses.pop(0)

    def interp_at(self, t_play):
        if not self._times:
            return None
        if t_play <= self._times[0]:
            return self._poses[0]
        if t_play >= self._times[-1]:
            return self._poses[-1]
        for i in range(len(self._times) - 1):
            t0 = self._times[i]
            t1 = self._times[i + 1]
            if t0 <= t_play <= t1:
                q0 = self._poses[i]
                q1 = self._poses[i + 1]
                span = t1 - t0
                if span <= 1e-9:
                    alpha = 0.0
                else:
                    alpha = (t_play - t0) / span
                return tuple(q0[j] + alpha * (q1[j] - q0[j]) for j in range(len(q0)))
        return self._poses[-1]


def _traj_merge_pose(cmd_dict, prev_deg, n_slots):
    out = [float(prev_deg[i]) if i < len(prev_deg) else 0.0 for i in range(n_slots)]
    for k, val in cmd_dict.items():
        ki = int(k)
        if 0 <= ki < n_slots:
            out[ki] = float(val)
    return tuple(out)


def _traj_reset():
    global _traj_anchor_us
    _traj_anchor_us = None
    if _traj_ring is not None:
        _traj_ring.clear()


def _parse_trajectory_prefix(line: str):
    """Return (t_seconds_or_None, remainder_after_comma)."""
    s = line.strip()
    if len(s) < 4:
        return None, s
    if s[0] != "T" and s[0] != "t":
        return None, s
    if s[1] != ":":
        return None, s
    i = 2
    while i < len(s) and s[i].isspace():
        i += 1
    j = i
    while j < len(s) and s[j] != ",":
        j += 1
    if j >= len(s):
        return None, s
    try:
        t_val = float(s[i:j])
    except ValueError:
        return None, s
    rest = s[j + 1 :].strip()
    return t_val, rest


def _traj_feed_sample(t_s, cmd_dict, axes):
    """Append a host trajectory knot; set wall-clock anchor on first sample."""
    global _traj_anchor_us, _traj_prev_deg, _traj_ring, _traj_slots
    if _traj_ring is None or _traj_slots <= 0:
        return
    merged = _traj_merge_pose(cmd_dict, _traj_prev_deg, _traj_slots)
    _traj_prev_deg = merged
    _traj_ring.push(t_s, merged)
    if _traj_anchor_us is None:
        _traj_anchor_us = time.ticks_us() - int(t_s * 1e6)


def _playback_traj_to_axes(axes):
    """Drive ``set_target_angle`` from interpolated ring playback time."""
    global _traj_anchor_us, _traj_ring
    if (
        _traj_ring is None
        or _traj_anchor_us is None
        or _traj_ring.empty()
        or not axes
    ):
        return
    t_stream_s = time.ticks_diff(time.ticks_us(), _traj_anchor_us) / 1e6
    t_play = t_stream_s - TRAJ_LOOKAHEAD_S
    pose = _traj_ring.interp_at(t_play)
    if pose is None:
        return
    for ax in axes:
        if hasattr(ax, "set_target_angle") and ax.idx < len(pose):
            ax.set_target_angle(pose[ax.idx])


def _traj_capture_prev_from_axes(axes):
    """After SYNC, seed interpolation tail from measured joint angles."""
    global _traj_prev_deg, _traj_slots
    if _traj_slots <= 0:
        _traj_prev_deg = ()
        return
    slot = [0.0] * _traj_slots
    for ax in axes:
        if ax.idx < _traj_slots and hasattr(ax, "idx"):
            slot[ax.idx] = _axis_angle_deg(ax)
    _traj_prev_deg = tuple(slot)


# ---------------------------------------------------------------------------
# Serial command parser
# ---------------------------------------------------------------------------

def parse_command(line: str):
    """Parse 'J0:45.00,J1:32.50,...' → {0: 45.0, 1: 32.5, ...}"""
    result = {}
    try:
        for token in line.strip().split(","):
            token = token.strip()
            if not token:
                continue
            key, val = token.split(":")
            result[int(key[1:])] = float(val)
        return result
    except Exception:
        return None


def _flush_stdout():
    try:
        sys.stdout.flush()
    except Exception:
        pass


def _poll_stdio_commands_nonblocking(poller, buf, handle_line_fn):
    """Drain USB lines during blocking WiFi join — keeps ``J0:…`` connect probes responsive."""
    try:
        while poller.poll(0):
            ch = sys.stdin.read(1)
            if ch is None:
                break
            if ch == "\n":
                line = buf.strip()
                buf = ""
                if line:
                    handle_line_fn(line, sys.stdout.write)
            else:
                buf += ch
                if len(buf) > 256:
                    buf = ""
    except Exception:
        pass
    return buf


def _wifi_sta_connect_blocking(stdin_poller=None, handle_line_fn=None, usb_buf_cell=None):
    """Join Wi‑Fi on the **main** thread.

    On Pico W / Pico 2 W (CYW43), calling ``wlan.connect`` only inside a newly
    spawned thread often never completes; association must run here before the
    TCP accept loop moves to a worker thread.

    Set ``WIFI_COUNTRY`` to a 2-letter ISO code (e.g. ``US``, ``GB``, ``DE``) so
    ``rp2.country()`` can enable the correct regulatory domain — required on many builds.

    Waits until ``ifconfig()[0]`` is not ``0.0.0.0`` (DHCP can lag ``isconnected()``).

    While waiting, drains USB stdin via *stdin_poller* so the host ``J0:…`` connect probe
    still receives ``OK`` (main motion loop has not started yet).
    """
    import network as _net

    _cc = str(WIFI_COUNTRY or "").strip().upper()
    try:
        import rp2

        if len(_cc) == 2:
            rp2.country(_cc)
            print("WiFi: rp2.country(%r) OK" % (_cc,))
        else:
            print(
                "WiFi: WARNING no WIFI_COUNTRY (need 2-letter ISO at Deploy: US, GB, DE, …)"
            )
    except Exception as _e:
        print("WiFi: rp2.country skipped (%s)" % (_e,))

    print("WiFi: ssid=%r" % (WIFI_SSID,))
    _flush_stdout()

    wlan = _net.WLAN(_net.STA_IF)
    wlan.active(True)
    try:
        wlan.disconnect()
    except Exception:
        pass
    time.sleep_ms(150)
    wlan.connect(WIFI_SSID, WIFI_PASSWORD)

    # Drain any USB commands already queued (PC probe often arrives immediately after banners).
    if stdin_poller is not None and handle_line_fn is not None and usb_buf_cell is not None:
        usb_buf_cell[0] = _poll_stdio_commands_nonblocking(
            stdin_poller, usb_buf_cell[0], handle_line_fn
        )

    # Up to ~60 s — association + DHCP on congested APs.
    for i in range(600):
        if stdin_poller is not None and handle_line_fn is not None and usb_buf_cell is not None:
            usb_buf_cell[0] = _poll_stdio_commands_nonblocking(
                stdin_poller, usb_buf_cell[0], handle_line_fn
            )
        try:
            _st = wlan.status()
        except Exception:
            _st = "?"
        if wlan.isconnected():
            ip = wlan.ifconfig()[0]
            if ip and ip != "0.0.0.0":
                _flush_stdout()
                return wlan
        if i > 0 and i % 50 == 0:
            print("WiFi: waiting status=%s (%ds) …" % (_st, i // 10))
            _flush_stdout()
        time.sleep(0.1)

    try:
        _st = wlan.status()
    except Exception:
        _st = "?"

    print(
        "WiFi connect failed status=%s — USB serial still works; "
        "check SSID/password, 2.4 GHz AP, WPA2, WIFI_COUNTRY (ISO 2-letter)"
        % (_st,)
    )
    _flush_stdout()
    try:
        wlan.active(False)
    except Exception:
        pass
    return None


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------

def main():
    # LEDs first — so they always blink even if motor config is bad
    # GP28 = last ADC pin, not used by any default motor config
    # NOTE: WiFi initialisation must come AFTER Pin("LED") is created.
    # On Pico 2W, Pin("LED") routes through the CYW43 chip — if you
    # disable WiFi first the LED pin object creation will fail.
    led = Pin("LED", Pin.OUT)

    # WiFi queues / STA handle — association runs **after** USB boot banners (can take tens of seconds).
    _wifi_rx = []
    _wifi_tx = []
    wlan_sta = None

    # Build axes — skip any joint whose pin config is invalid
    axes = []
    for cfg in JOINTS:
        try:
            axes.append(make_axis(cfg))
        except Exception as e:
            print(f"WARN: skipping joint {cfg.get('idx','?')}: {e}")

    _apply_host_follow_sps_cap(axes)

    global _traj_ring, _traj_slots, _traj_prev_deg, _traj_anchor_us
    _traj_slots = max((ax.idx for ax in axes), default=-1) + 1 if axes else 0
    _traj_prev_deg = tuple([0.0] * _traj_slots)
    _traj_anchor_us = None
    _traj_ring = TrajectoryRing()

    global _http_axes_ref
    _http_axes_ref = axes

    buf = ""
    idle_ticks = 0
    # Control period target (µs); actual inter-tick time is measured below so host-follow
    # max_sps matches wall-clock even when one loop iteration overruns STEP_US or catches up.

    # Position stream state
    _pos_stream_enabled = False
    _last_reply_fn = sys.stdout.write   # track which transport to push POS data to
    _pos_stream_last_ms = time.ticks_ms()

    # Pin debug stream state
    _pin_stream_enabled = False
    _pin_stream_last_ms = time.ticks_ms()

    # Homing state
    _homing_active = False

    # Non-blocking poll — avoids sys.stdin.read(1) blocking the whole loop
    _poller = select.poll()
    _poller.register(sys.stdin, select.POLLIN)

    # ── Command dispatcher ──────────────────────────────────────────────────
    # Defined once here (not inside the loop) so MicroPython does not
    # allocate and GC a new function object on every main-loop iteration.
    def _handle_line(line, reply_fn):
        nonlocal idle_ticks, _pos_stream_enabled, _last_reply_fn, _pin_stream_enabled, _homing_active
        _last_reply_fn = reply_fn   # track active transport for position push
        _words = line.split()
        if line == "PING":
            reply_fn("Robot Arm Pico Controller ready\n")
            reply_fn("firmware ready\n")
        elif line == "WIFI":
            # Re-print association result if serial console missed boot-time logs.
            try:
                import network as _wn

                _w = _wn.WLAN(_wn.STA_IF)
                if _w.isconnected():
                    _ip = _w.ifconfig()[0]
                    if _ip and _ip != "0.0.0.0":
                        reply_fn("WiFi connected: %s\n" % _ip)
                    else:
                        reply_fn(
                            "WiFi: linked but no IP yet (ifconfig=%s) status=%s\n"
                            % (_w.ifconfig(), _w.status())
                        )
                else:
                    reply_fn("WiFi: not connected status=%s\n" % _w.status())
            except Exception as _e:
                reply_fn("ERR:WIFI:%s\n" % _e)
        elif line == "LED_TOGGLE":
            led.toggle()
            reply_fn("OK\n")
        elif line == "MEM":
            import gc
            reply_fn("MEM:%d bytes free\n" % gc.mem_free())
        elif line == "TEMP":
            # On-die sensor on ADC(4) — typical RP2040/Pico 1 formula (see RP datasheet)
            try:
                import machine
                adc = machine.ADC(4)
                v = adc.read_u16() * 3.3 / 65535.0
                t_c = 27.0 - (v - 0.706) / 0.001721
                reply_fn("TEMP:%.1fC (on-die)\n" % t_c)
            except Exception as e:
                reply_fn("ERR:TEMP:%s\n" % e)
        elif line == "REBOOT":
            reply_fn("Rebooting...\n")
            time.sleep(0.1)
            import machine as _m; _m.reset()
        elif line == "POS_STREAM_ON":
            _pos_stream_enabled = True
            reply_fn("OK\n")
        elif line == "POS_STREAM_OFF":
            _pos_stream_enabled = False
            reply_fn("OK\n")
        elif line == "PIN_STREAM_ON":
            _pin_stream_enabled = True
            reply_fn("OK\n")
        elif line == "PIN_STREAM_OFF":
            _pin_stream_enabled = False
            reply_fn("OK\n")
        elif line == "STOP":
            # Cancel all active sequences and stop all motors immediately
            _homing_active = False
            _pos_stream_enabled = False
            _pin_stream_enabled = False
            _traj_reset()
            for axis in axes:
                axis._homing_mode = False
                axis._homing_stage = "approach"
                if hasattr(axis, "_homing_last_stage"):
                    axis._homing_last_stage = ""
                if hasattr(axis, "clear_host_follow_rates"):
                    axis.clear_host_follow_rates()
                elif hasattr(axis, "_host_sps_accum"):
                    axis._host_sps_accum = 0.0
                axis.velocity = 0.0
                axis.target_pos = axis.current_pos  # cancel any pending move
            reply_fn("STOPPED\n")
        elif line == "HOME":
            # Initiate homing on all axes that have a home switch
            for axis in axes:
                if axis._home_pin is not None:
                    axis._homing_mode = True
                    axis._homing_stage = "approach"
                    axis._homing_last_stage = ""
                    if hasattr(axis, "clear_host_follow_rates"):
                        axis.clear_host_follow_rates()
                    axis.at_home = False
                    reply_fn("HOME J{}: pin={} dir={} search={} fine={} backup={}\n".format(
                        axis.idx, axis.home_pin_num, axis.home_direction,
                        axis.home_search_speed_sps, axis.home_speed_sps, axis.home_backup_steps))
            _homing_active = True
            idle_ticks = 0
            reply_fn("HOMING\n")
        elif line.startswith("HOMEJ"):
            # Per-joint homing: HOMEJ<n> [dir] [speed]
            # e.g. HOMEJ0, HOMEJ0 -1, HOMEJ0 -1 10
            try:
                rest = line[5:].strip()
                parts = rest.split()
                jn = int(parts[0])
                target_axis = None
                for axis in axes:
                    if axis.idx == jn:
                        target_axis = axis
                        break
                if target_axis is None:
                    reply_fn("ERR:no axis J{}\n".format(jn))
                elif target_axis._home_pin is None:
                    reply_fn("ERR:J{} has no home switch\n".format(jn))
                else:
                    if len(parts) >= 2:
                        d = int(parts[1])
                        target_axis.home_direction = 1 if d >= 0 else -1
                    # HOMEJ<n> [dir] [search_sps] [fine_sps]  — e.g. HOMEJ0 -1 200 10
                    if len(parts) >= 3:
                        v_search = float(parts[2])
                        target_axis.home_search_speed_sps = v_search
                        if len(parts) >= 4:
                            target_axis.home_speed_sps = float(parts[3])
                        else:
                            target_axis.home_speed_sps = v_search
                    target_axis._homing_mode = True
                    target_axis._homing_stage = "approach"
                    target_axis._homing_last_stage = ""
                    if hasattr(target_axis, "clear_host_follow_rates"):
                        target_axis.clear_host_follow_rates()
                    target_axis.at_home = False
                    _homing_active = True
                    idle_ticks = 0
                    reply_fn("HOMING J{}: pin={} dir={} search={} fine={} backup={}\n".format(
                        target_axis.idx, target_axis.home_pin_num,
                        target_axis.home_direction,
                        target_axis.home_search_speed_sps, target_axis.home_speed_sps,
                        target_axis.home_backup_steps))
            except (ValueError, IndexError) as e:
                reply_fn("ERR:bad HOMEJ: {}\n".format(e))
        elif line.startswith("SYNC:"):
            # Host: assume mechanical pose matches these angles (no step burst). See PC connect.
            # Never apply during homing — SYNC clears _homing_mode and would race the state machine
            # (wrong direction / slamming through the home switch when the PC reconnects mid-HOME).
            try:
                if _homing_active or any(
                    getattr(ax, "_homing_mode", False) for ax in axes
                ):
                    reply_fn("ERR:SYNC:homing_busy\n")
                else:
                    rest = line[5:].strip()
                    cmd = parse_command(rest)
                    if cmd is None:
                        reply_fn("ERR:bad SYNC\n")
                    else:
                        _traj_reset()
                        for axis in axes:
                            if axis.idx not in cmd:
                                continue
                            a = cmd[axis.idx]
                            axis._homing_mode = False
                            axis._homing_stage = "approach"
                            if hasattr(axis, "_homing_last_stage"):
                                axis._homing_last_stage = ""
                            if hasattr(axis, "angle_to_steps"):
                                s = axis.angle_to_steps(a)
                                axis.current_pos = s
                                axis.target_pos = s
                                if hasattr(axis, "clear_host_follow_rates"):
                                    axis.clear_host_follow_rates()
                                elif hasattr(axis, "_host_sps_accum"):
                                    axis._host_sps_accum = 0.0
                            else:
                                axis.set_target_angle(a)
                        _homing_active = False
                        idle_ticks = 0
                        _traj_capture_prev_from_axes(axes)
                        reply_fn("OK\n")
            except Exception as e:
                reply_fn("ERR:SYNC:%s\n" % e)
        elif _words and _words[0].upper() == "MOTORINFO":
            # What driver + GPIOs this build uses (verify against wiring; compare to Deploy / motor_config)
            for ax in axes:
                reply_fn(_axis_wiring_line(ax) + "\n")
            if not axes:
                reply_fn("ERR:no axes — JOINTS empty or all make_axis() failed; check main.py / Deploy\n")
            reply_fn("NOTE:3.3V GPIO — many 5V-only driver boards need a level shifter for STEP/DIR/EN to register.\n")
            _cap_note = (
                "HOST_FOLLOW_MAX_SPS={} (0=off) — scales steppers so peak joint ≤ this rate, "
                "others proportional.\n".format(HOST_FOLLOW_MAX_SPS)
            )
            reply_fn(_cap_note)
            reply_fn(
                "NOTE:host-follow ramps with JOINTS accel (steps/s²), optional jerk (steps/s³), and max_sps.\n"
            )
            reply_fn(
                "NOTE:host may stream ``T:<stream_s>,J0:…`` for buffered interpolation (~{:g} ms lookahead).\n".format(
                    TRAJ_LOOKAHEAD_S * 1000.0
                )
            )
            reply_fn(
                "NOTE:STEP/DIR axes use PIO STEP by default (``pio_stepdir`` true); "
                "GPIO STEP only if ``pio_stepdir`` false (debug).\n"
            )
            reply_fn(
                "NOTE:burst ceiling ≤{0} steps/tick/axis; STEP_US={1}µs main period (raise STEP_US if overruns).\n".format(
                    MAX_STEPS_PER_AXIS_TICK, STEP_US
                )
            )
            reply_fn("HINT:default main.py is 28BYJ on GP2–5 for J0. After Deploy, STEPT uses *your* STEP/DIR pins above.\n")
            reply_fn("OK\n")
        elif _words and _words[0].upper() == "PRINTAXES":
            # Same as boot line; use if the serial log scrolled away
            if axes:
                reply_fn("AXES {}: {}\n".format(
                    len(axes), " | ".join(_axis_wiring_line(a) for a in axes)))
            else:
                reply_fn("AXES 0: no motors (fix JOINTS / Deploy)\n")
            reply_fn("OK\n")
        elif _words and _words[0].upper() == "STEPT":
            # Raw open-loop step pulses for hardware debug: STEPT <jn> <count> [BWD]
            try:
                parts = _words
                if len(parts) < 3:
                    reply_fn("ERR:STEPT <joint> <count> [BWD]  e.g. STEPT 0 100\n")
                else:
                    jn = int(parts[1])
                    cnt = min(5000, max(1, int(parts[2])))
                    _fwd = True
                    if len(parts) > 3 and parts[3].upper() in ("BWD", "REV", "BACK"):
                        _fwd = False
                    _axs = [a for a in axes if a.idx == jn]
                    if not _axs:
                        reply_fn("ERR:no axis J{}\n".format(jn))
                    elif not hasattr(_axs[0], "_step"):
                        reply_fn("ERR:J{} not a stepper (no _step)\n".format(jn))
                    else:
                        _a = _axs[0]
                        for _ in range(cnt):
                            _a._step(1, _fwd)
                        _t = type(_a).__name__
                        if _t == "StepperAxisStepDir":
                            _ps = "STEP=GP{} DIR=GP{}".format(
                                _a._step_pin_num, _a._dir_pin_num
                            )
                        elif _t == "StepperAxisStepDirPIO":
                            _ps = "STEP=GP{}(PIO) DIR=GP{}".format(
                                _a._step_pin_num, _a._dir_pin_num
                            )
                        elif _t == "StepperAxis28BYJ":
                            _ps = "28BYJ IN={}".format(_a._pin_nums)
                        else:
                            _ps = _t
                        reply_fn("OK STEPT J{} {}x{}  {}  (these GPIOs were toggled)\n".format(
                            jn, "FWD" if _fwd else "BWD", cnt, _ps
                        ))
            except (ValueError, IndexError) as e:
                reply_fn("ERR:STEPT: {}\n".format(e))
        else:
            t_stream, rest = _parse_trajectory_prefix(line)
            if t_stream is not None:
                cmd = parse_command(rest)
                if cmd is not None:
                    _traj_feed_sample(t_stream, cmd, axes)
                    idle_ticks = 0
                    reply_fn("OK\n")
                else:
                    reply_fn("ERR:bad trajectory sample\n")
            else:
                cmd = parse_command(line)
                if cmd is not None:
                    loaded = {a.idx for a in axes}
                    for jn in cmd:
                        if jn not in loaded and jn not in _SEEN_UNLOADED_J_CMD:
                            _SEEN_UNLOADED_J_CMD.add(jn)
                            print(
                                "WARN: host sends J{0} but no motor for that index "
                                "(see boot for 'skipping joint' or Deploy with all joints; "
                                "STEPT {0} 50 to test if axis exists)\n".format(jn)
                            )
                    for axis in axes:
                        if axis.idx in cmd:
                            axis.set_target_angle(cmd[axis.idx])
                    idle_ticks = 0
                    reply_fn("OK\n")
                else:
                    reply_fn("ERR:bad command\n")



    print("Robot Arm Pico Controller ready")
    print("firmware ready")
    if axes:
        print("AXES_LOADED: {} | {}".format(
            len(axes), " | ".join(_axis_wiring_line(a) for a in axes)))
    else:
        print("AXES_LOADED: 0 — no motors: fix JOINTS in main.py or Deploy from the PC GUI")

    if ENABLE_WIFI and WIFI_SSID:
        import _thread as _thread_mod
        import socket as _socket

        print("WiFi: joining {} …".format(WIFI_SSID))
        _flush_stdout()
        usb_buf_cell = [buf]
        wlan_sta = _wifi_sta_connect_blocking(_poller, _handle_line, usb_buf_cell)
        buf = usb_buf_cell[0]
        if wlan_sta is not None:
            _sta_ip = wlan_sta.ifconfig()[0]
            print("WiFi connected: {}".format(_sta_ip))
            _flush_stdout()

            def _wifi_tcp_loop():
                port = TCP_PORT
                tcp_candidates = []
                if _sta_ip and _sta_ip != "0.0.0.0":
                    tcp_candidates.append((_sta_ip, port))
                tcp_candidates.append(("", port))

                srv = None
                last_tcp_e = None
                for taddr in tcp_candidates:
                    tsock = None
                    try:
                        tsock = _socket.socket()
                        tsock.setsockopt(_socket.SOL_SOCKET, _socket.SO_REUSEADDR, 1)
                        tsock.bind(taddr)
                        srv = tsock
                        tsock = None
                        print(
                            "TCP control listening on {}:{}".format(taddr[0] or "*", port)
                        )
                        break
                    except OSError as te:
                        last_tcp_e = te
                        if tsock is not None:
                            try:
                                tsock.close()
                            except Exception:
                                pass

                if srv is None:
                    try:
                        print("ERR: TCP bind failed — {}".format(last_tcp_e))
                        _flush_stdout()
                    except Exception:
                        pass
                    return

                srv.listen(4)
                srv.settimeout(1)
                _flush_stdout()

                conn = [None]
                tcp_buf = [""]

                def _do_upload(c):
                    """Receive firmware over TCP and write to main.py, then reset.

                    Protocol (all lines terminated with \\n):
                      Host → Pico: UPLOAD_BEGIN <total_bytes>
                      Pico → Host: UPLOAD_READY
                      Host → Pico: UPLOAD_CHUNK <hex_data>   (repeat)
                      Pico → Host: UPLOAD_ACK                (for each chunk)
                      Host → Pico: UPLOAD_END
                      Pico → Host: UPLOAD_DONE
                      Pico resets.
                    """
                    import machine as _machine
                    c.settimeout(10.0)
                    buf = tcp_buf[0]   # carry over any bytes already buffered
                    try:
                        f = open("main_upload.py", "wb")
                        c.sendall(b"UPLOAD_READY\n")
                        while True:
                            # Read until we have a complete line
                            while "\n" not in buf:
                                chunk = c.recv(512)
                                if not chunk:
                                    f.close()
                                    return
                                buf += chunk.decode("utf-8", "replace")
                            line, buf = buf.split("\n", 1)
                            line = line.strip()
                            if line.startswith("UPLOAD_CHUNK "):
                                hex_data = line[13:]
                                f.write(bytes.fromhex(hex_data))
                                c.sendall(b"UPLOAD_ACK\n")
                            elif line == "UPLOAD_END":
                                f.close()
                                import os as _os
                                _os.rename("main_upload.py", "main.py")
                                c.sendall(b"UPLOAD_DONE\n")
                                time.sleep(0.3)
                                _machine.reset()
                            # ignore unknown lines
                    except Exception:
                        try:
                            f.close()
                        except Exception:
                            pass

                while True:
                    # Accept new connection if we have none
                    if conn[0] is None:
                        try:
                            c, _ = srv.accept()
                            c.settimeout(0.05)
                            try:
                                # LAN clients (PicoWifiInterface) wait for this on TCP — USB prints differ.
                                c.sendall(
                                    b"Robot Arm Pico Controller ready\nfirmware ready\n"
                                )
                            except OSError:
                                try:
                                    c.close()
                                except Exception:
                                    pass
                                continue
                            conn[0] = c
                            tcp_buf[0] = ""
                        except OSError:
                            pass

                    if conn[0] is not None:
                        # Read incoming data. On RST or fatal errors, close the slot —
                        # otherwise conn stays non-None and accept() never runs again
                        # (host sees TCP connect but no firmware-ready banner).
                        data = None
                        try:
                            data = conn[0].recv(256)
                        except OSError as e:
                            _en = getattr(e, "errno", None)
                            if _en is None and e.args:
                                try:
                                    _en = int(e.args[0])
                                except (TypeError, ValueError):
                                    _en = None
                            _timeout_like = False
                            if _en is not None:
                                if _en == errno.EAGAIN:
                                    _timeout_like = True
                                elif getattr(errno, "EWOULDBLOCK", None) == _en:
                                    _timeout_like = True
                                elif getattr(errno, "ETIMEDOUT", None) == _en:
                                    _timeout_like = True
                                elif _en in (11, 116):
                                    # lwIP / ports using numeric EAGAIN / ETIMEDOUT
                                    _timeout_like = True
                            if not _timeout_like:
                                try:
                                    conn[0].close()
                                except Exception:
                                    pass
                                conn[0] = None
                                tcp_buf[0] = ""

                        if conn[0] is not None and data is not None:
                            if data == b"":       # client closed connection
                                conn[0].close()
                                conn[0] = None
                                tcp_buf[0] = ""
                            elif data:
                                tcp_buf[0] += data.decode("utf-8", "replace")
                                while "\n" in tcp_buf[0]:
                                    line, tcp_buf[0] = tcp_buf[0].split("\n", 1)
                                    stripped = line.strip()
                                    if not stripped:
                                        continue
                                    if stripped.startswith("UPLOAD_BEGIN"):
                                        _do_upload(conn[0])
                                        conn[0].close()
                                        conn[0] = None
                                        tcp_buf[0] = ""
                                        break
                                    else:
                                        _wifi_rx.append(stripped)

                        if conn[0] is not None:
                            while _wifi_tx:
                                resp = _wifi_tx.pop(0)
                                try:
                                    conn[0].sendall(resp.encode())
                                except OSError:
                                    conn[0].close()
                                    conn[0] = None
                                    break

            try:
                _thread_mod.stack_size(12 * 1024)
            except Exception:
                pass
            _thread_mod.start_new_thread(_wifi_tcp_loop, ())
            try:
                _thread_mod.stack_size(12 * 1024)
            except Exception:
                pass
            try:
                _thread_mod.start_new_thread(_web_http_server_thread, (_sta_ip,))
                print(
                    "HTTP dashboard (same LAN): http://{}:{}".format(
                        _sta_ip,
                        WEB_HTTP_PORT,
                    )
                )
                _flush_stdout()
            except Exception as _we:
                print("WARN: web dashboard thread:", _we)
                try:
                    import sys as _sys

                    _sys.print_exception(_we)
                except Exception:
                    pass

    loop_prev_start = time.ticks_us()
    first_loop_iter = True
    # Rate-limit repeated ERR:main lines (same error every 20 ms otherwise floods host)
    _err_last_key = None
    _err_last_ms = 0

    while True:
        try:
            t_loop_start = time.ticks_us()
            if first_loop_iter:
                du_us = STEP_US
                first_loop_iter = False
            else:
                du_us = time.ticks_diff(t_loop_start, loop_prev_start)
            loop_prev_start = t_loop_start
            if du_us <= 0:
                du_us = STEP_US
            # Stall / attach debugger: do not credit more than ~10 ms in one tick
            _max_du = STEP_US * 40
            if du_us > _max_du:
                du_us = _max_du
            tdt = max(float(du_us) * 1e-6, 1e-9)
            _t_nom_s = float(STEP_US) * 1e-6
            _t_max_s = _t_nom_s * _MOTION_DT_MAX_MULT
            if tdt > _t_max_s:
                tdt = _t_max_s

            _playback_traj_to_axes(axes)

            # ── 1. Advance all motor axes (28BYJ: GPIO coils; stepdir: PIO STEP unless pio_stepdir false)
            any_moving = False
            if _HOST_INTERLEAVE_STEPS:
                for axis in axes:
                    if getattr(axis, "_homing_mode", False):
                        axis.update(tdt)
                    elif hasattr(axis, "_interleave_plan_host_steps"):
                        axis._interleave_plan_host_steps(tdt)
                    else:
                        axis.update(tdt)
                # Round-robin up to one step per axis per pass until no axis has budget/error left.
                _max_ir = (len(axes) * MAX_STEPS_PER_AXIS_TICK * 4) + 8
                _ir = 0
                while _ir < _max_ir:
                    _ir += 1
                    any_emit = False
                    for axis in axes:
                        left = getattr(axis, "_interleave_left", 0)
                        if left <= 0:
                            continue
                        n_em = axis._emit_n_toward_target(1)
                        if n_em:
                            axis._interleave_left = left - 1
                            any_emit = True
                        else:
                            axis._interleave_left = 0
                    if not any_emit:
                        break
                for axis in axes:
                    if hasattr(axis, "_finalize_interleave_host") and not getattr(
                        axis, "_homing_mode", False
                    ):
                        axis._finalize_interleave_host(tdt)
            else:
                for axis in axes:
                    axis.update(tdt)
            for axis in axes:
                if getattr(axis, "_homing_mode", False):
                    any_moving = True
                elif hasattr(axis, "_steps_out") and abs(axis.target_pos - axis.current_pos) > 0.5:
                    any_moving = True

            # ── 2. USB serial (non-blocking); WiFi only if ENABLE_WIFI ───────────
            try:
                while _poller.poll(0):
                    ch = sys.stdin.read(1)
                    if ch is None:
                        break
                    if ch == "\n":
                        line = buf.strip()
                        buf = ""
                        _handle_line(line, sys.stdout.write)
                    else:
                        buf += ch
                        if len(buf) > 256:
                            buf = ""
            except Exception:
                pass

            if ENABLE_WIFI and WIFI_SSID:
                while _wifi_rx:
                    line = _wifi_rx.pop(0)
                    _handle_line(line, _wifi_tx.append)

            while _web_cmd_queue:
                try:
                    _apply_web_command(_web_cmd_queue.pop(0), axes)
                except Exception:
                    pass

            # ── 3. Optional 1 Hz POS / PINS (skip ticks_ms when both off) ─────────
            if _pos_stream_enabled or _pin_stream_enabled:
                now_ms = time.ticks_ms()
                if _pos_stream_enabled and time.ticks_diff(now_ms, _pos_stream_last_ms) >= 1000:
                    _pos_stream_last_ms = now_ms
                    parts = []
                    for ax in axes:
                        if hasattr(ax, "current_pos") and hasattr(ax, "_steps_out") and ax._steps_out > 0:
                            angle_deg = ax.current_pos / ax._steps_out * 360.0 + ax.zero_offset
                        else:
                            angle_deg = 0.0
                        parts.append("J{}:{:.2f}".format(ax.idx, angle_deg))
                    _last_reply_fn("POS:" + ",".join(parts) + "\n")

                if _pin_stream_enabled and time.ticks_diff(now_ms, _pin_stream_last_ms) >= 1000:
                    _pin_stream_last_ms = now_ms
                    parts = []
                    for ax in axes:
                        # Live limit-switch reading (not the stale at_home flag)
                        limit_status = ""
                        if hasattr(ax, '_home_pin') and ax._home_pin is not None:
                            pin_val = ax._home_pin.value()
                            live_active = (pin_val == 1) if ax.home_pin_polarity == "NC" else (pin_val == 0)
                            limit_status = " LIMIT:{}".format("HOME" if live_active else "none")
                        homing_status = ""
                        if getattr(ax, '_homing_mode', False):
                            homing_status = " HOMING:{} vel={:.0f}".format(
                                ax._homing_stage, ax.velocity)
                        if hasattr(ax, "get_pin_debug"):
                            parts.append("J{}: {}{}{}".format(
                                ax.idx, ax.get_pin_debug(), limit_status, homing_status))
                    _last_reply_fn("PINS: " + "  |  ".join(parts) + "\n")

            # ── 3c. Check homing completion ──────────────────────────────────────
            # Homing is done when no axis is still in _homing_mode.
            # The state machine clears _homing_mode when the precision stage contacts home.
            if _homing_active:
                still_homing = False
                for ax in axes:
                    if getattr(ax, '_homing_mode', False):
                        still_homing = True
                        break
                if not still_homing:
                    _homing_active = False
                    _last_reply_fn("HOMING_COMPLETE\n")
    
            # ── 4. De-energise coils after ~2 s of idleness ─────────────────────
            if not any_moving:
                idle_ticks += 1
                if idle_ticks > 8000:   # 8000 × 250 µs = 2 s (scale with STEP_US if you change it)
                    for axis in axes:
                        try:
                            d = getattr(axis, "deenergise", None)
                            if d is not None:
                                d()
                        except Exception:
                            pass
                    idle_ticks = 0
            else:
                idle_ticks = 0
    
            # ── 5. Sleep for the remainder of the STEP_US period (from loop start) ─
            # Wall time between loop starts feeds du_us → tdt, but tdt is capped (above) so a
            # single iteration never integrates more than a few nominal periods (avoids post-lag
            # surges). Still sleep from this iteration's start so STEP_US remains the *target* cadence.
            _elapsed_loop = time.ticks_diff(time.ticks_us(), t_loop_start)
            _rem_us = STEP_US - _elapsed_loop
            if _rem_us > 0:
                time.sleep_us(_rem_us)

        except Exception as _main_exc:
            try:
                _e2 = str(_main_exc).replace("\n", " ")[:200]
                _k = str(type(_main_exc).__name__) + _e2
                _now = time.ticks_ms()
                if _err_last_key != _k or time.ticks_diff(_now, _err_last_ms) > 3000:
                    sys.stdout.write("ERR:main:%s:%s\n" % (type(_main_exc).__name__, _e2))
                    _err_last_key = _k
                    _err_last_ms = _now
            except Exception:
                pass
            time.sleep_ms(20)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
