"""Single source of truth for the terminal HELP lines (kept in sync with the dispatcher in gui)."""

TERMINAL_HELP_LINES = [
    "Available commands:",
    "─── Info & diagnostics ─────────────────────────────────────",
    "  HELP                     — show this list",
    "  STATUS                   — full system snapshot",
    "  HISTORY                  — recent command history (same as ↑ in the input line)",
    "  JOINTS                   — all joint angles (deg + rad)",
    "  LINKS                    — list link lengths",
    "  MOTORS                   — motor config table",
    "  REACH                    — current reach vs max reach",
    "  DIST                     — EE distance to current target",
    "  BBOX                     — approximate workspace bounding box",
    "  NEAREST                  — closest reachable point to target",
    "  STATS                    — collision / singularity check",
    "  LIMITS                   — show joint angle limits (* = custom)",
    "  SETLIMIT J<n> <min> <max> — set joint n limits in degrees",
    "  RESETLIMITS              — reset all limits to ±170°",
    "  TARGET                   — print current IK target",
    "  FK                       — forward kinematics dump",
    "  LATENCY                  — measure Pico round-trip time",
    "─── Display streams ────────────────────────────────────────",
    "  POS                      — toggle 1 Hz joint-angle stream",
    "  SENDPOS / SENDPOS ON/OFF — stream outgoing joint angles on every change (hardware only)",
    "  EE / EE ON / EE OFF      — toggle 1 Hz EE coordinate stream",
    "  PINS / PINS ON / PINS OFF — toggle 1 Hz GPIO pin debug stream (hw only)",
    "  LIMSWITCH / LIMSWITCH ON / OFF — toggle limit switch status stream (debug homing)",
    "  STOP                     — cancel homing, stop all motors and streams",
    "─── Motion ─────────────────────────────────────────────────",
    "  HOME                     — animate to vertical (all joints 0)",
    "  PARK                     — fold arm to compact stowed pose",
    "  EXTEND                   — fully extend all joints (max reach)",
    "  FLIP                     — toggle elbow up/down",
    "  ELBOW UP|DOWN            — set elbow configuration",
    "  PAUSE                    — pause running animation",
    "  RESUME                   — resume paused animation",
    "  STOP                     — stop animation / sequence",
    "  SPEED <0.1-5.0>          — animation speed multiplier",
    "  JOG J<n> <deg> [ABS]     — jog joint: relative ±deg, or absolute with ABS",
    "  JOG X|Y|Z <dist>         — jog IK target          (JOG Z -10)",
    "  NUDGE <axis> <val>       — alias for JOG (smaller increments)",
    "  j0 20  /  j0 20 abs      — shorthand: JOG J0 20  (rel)  or  SETJOINT (abs) with abs",
    "  !j0 20                    — same as SETJOINT J0 20 (absolute °; not a relative move)",
    "  x 10  /  y -2  /  z 5    — shorthand: jog IK target in mm  (JOG X|Y|Z)",
    "  SETJOINT J<n> <deg>      — set joint to absolute angle (same as JOG … ABS)",
    "  GOTO <x> <y> <z>         — set absolute IK target",
    "  SWEEP J<n> <s> <e> [n]   — sweep joint s°→e° in n steps",
    "  SOLVE                    — re-run IK for current target",
    "─── Waypoints ──────────────────────────────────────────────",
    "  WAYPOINTS                — list loaded waypoints",
    "  WP <n>                   — jump to waypoint n (1-based)",
    "  ADDWP                    — add current EE as waypoint",
    "  CLEARWP                  — clear all waypoints",
    "  CLEARPATH                — alias for CLEARWP",
    "  LOOP / LOOP ON / OFF     — toggle waypoint loop",
    "  RUN                      — start waypoint sequence",
    "  PLOTPATH                 — 2D matplotlib chart of waypoints",
    "─── Named poses ───────────────────────────────────────────",
    "  SAVEPOSE <name>          — save current joint angles",
    "  LOADPOSE <name>          — restore saved pose",
    "  POSES                    — list all saved poses",
    "  DELETEPOSE <name>        — remove a saved pose",
    "  DIFFPOSE <name>          — angle delta: current vs saved",
    "  COMPARE <a> <b>          — angle delta between two saved poses",
    "  STARTPOSE                — snap 3D sim to saved starting pose (config starting_angles / last load)",
    "─── Config ─────────────────────────────────────────────────",
    "  CONFIG                   — dump full arm config as JSON",
    "  ZERO                     — capture current pose as zero offsets",
    "  SAVE                     — save all configs immediately",
    "  RESET                    — prompt to reset all to defaults",
    "  SETLINK <i> <len>        — change link i length",
    "  SETBASE <height>         — set base vertical offset",
    "  SETOFFSET <j> <mm>       — set joint j plane offset",
    "  MARGIN <val>             — set collision margin",
    "  ACCEL <sps²>             — set motor acceleration (all joints)",
    "  CONSTRAINT / ON / OFF    — toggle EE orientation constraint",
    "─── Hardware ───────────────────────────────────────────────",
    "  CONNECT                  — USB serial only (uses Hardware panel COM port)",
    "  DISCONNECT               — disconnect from hardware",
    "  RECONNECT                — disconnect then reconnect",
    "  WIFI                     — panel bookmark + SSID; if USB-connected, forwards WIFI → Pico prints IP",
    "  SETPORT <n>              — firmware LAN TCP port for Deploy (desktop does not use Wi‑Fi TCP)",
    "  BROADCAST                — scan subnet for Pico on firmware TCP port (discovery only)",
    "  DEPLOY                   — USB firmware deploy (mpremote / REPL)",
    "  (Wireless control: browser http://<pico-ip>:8080 — not TCP from this desktop app)",
    "  REBOOT                   — soft-reset the Pico",
    "  PING                     — check Pico is alive",
    "  MOTORINFO                — each joint: driver + STEP/DIR GPIOs (3.3V note)",
    "  PRINTAXES                — repeat AXES_LOADED line (which GPIOs each J uses)",
    "  STEPT <j> <n> [BWD]      — raw n step pulses (proves PUL/DIR vs angle-stream jog)",
    "  (GUI: 'Enable hardware synchronization' must be ON for JOG/IK/waypoints; OFF = no J0:… stream; homing/LED/STOP still work)",
    "  (Joint J2 dead: run PRINTAXES — all joints must be listed. If J2 is missing, re-Deploy; check boot for 'skipping joint 2'. STEPT 2 200 tests that motor/GPIO. Host streams J0..J(n-1); n = Arm links+1, must match Motor rows.)",
    "  (DIR = steady; STEP = fast edges — a DMM is poor to see STEP; use PINS or scope)",
    "  LATENCY                  — measure round-trip ping time",
    "  LED_TOGGLE               — toggle onboard LED",
    "  MEM                      — Pico free memory",
    "  TEMP                     — Pico CPU temperature",
    "  LOG [n]                  — last n lines of hardware_log.txt",
    "  LOG LEVEL <lvl>          — set log verbosity (DEBUG/INFO/WARN)",
    "─── Scripting ──────────────────────────────────────────────",
    "  ALIAS <name> <cmd>       — define a command shorthand",
    "  ALIASES                  — list defined aliases",
    "  MACRO <name> <c1;c2;…>   — define a named sequence",
    "  MACROS                   — list defined macros",
    "  EXEC <name>              — run a macro",
    "  REPEAT <n> <cmd>         — repeat command n times (≤50)",
    "  LOAD <file>              — run commands from a .txt file",
    "  WATCH <s> <cmd>          — auto-repeat cmd every s seconds",
    "  WATCH STOP               — stop WATCH",
    "─── Viewport ───────────────────────────────────────────────",
    "  ZOOM <val>               — set camera distance",
    "  CAMERA <preset>          — ISO / TOP / FRONT / SIDE / BACK",
    "  SCREENSHOT               — save viewport as PNG",
    "─── Terminal ───────────────────────────────────────────────",
    "  CLEAR                    — clear terminal output",
    "  ECHO <text>              — print text to terminal",
    "  MARK [label]             — timestamp divider",
    "  UPTIME                   — session duration HH:MM:SS",
    "  VERSION                  — Python / PyQt6 version info",
    "  EXPORT [filename]        — save terminal log to file",
    "  HISTORY                  — recent command history (same as ↑ in the input line)",
    "  <any other text>         — sent verbatim to hardware",
]
